/* 냉장고 사전 데이터 — build.js와 index.html이 공유
   rt/fr/fz: 실온/냉장/냉동 (개봉·손질 후 기준)
   null=비권장·불가, "inf"=무기한, [min,max,unit] unit: h시간 d일 w주 M개월 y년
   tip=보관법, exp=기한 노트, bad=상한 신호, fzt=냉동·해동법(또는 비권장 이유) */
const FOODS = [
/* ---- 채소 veg (20) ---- */
{id:"양파",ko:"양파",en:"Onion",e:"🧅",g:"veg",rt:[1,2,"M"],fr:[1,2,"w"],fz:[6,null,"M"],
 tip:["통풍되는 서늘하고 어두운 곳에 망째 걸어두는 게 최선이에요. 깐 양파만 밀폐해 냉장하세요.","Hang in mesh in a cool, dark, airy spot; refrigerate only peeled onions, sealed."],
 exp:["표시 기한보다 상태가 기준이에요 — 단단하고 냄새 없으면 대부분 괜찮아요.","Condition beats the printed date — firm and odor-free usually means fine."],
 bad:["물컹해지거나 갈색 진물, 시큼한 냄새, 검은 곰팡이가 보이면 버리세요.","Toss if mushy, oozing brown, sour-smelling, or showing black mold."],
 fzt:["다지거나 채 썰어 소분 냉동하면 볶음용으로 6개월 이상 써요. 생 식감은 사라져요.","Dice and freeze in portions — 6+ months for cooking; the raw crunch is gone."]},
{id:"마늘",ko:"마늘",en:"Garlic",e:"🧄",g:"veg",rt:[3,6,"M"],fr:[1,2,"w"],fz:[6,null,"M"],
 tip:["통마늘은 껍질째 서늘하고 어두운 곳에. 깐 마늘은 밀폐 냉장, 다진 마늘은 바로 냉동이 정석이에요.","Whole heads keep in a cool dark place; peeled cloves sealed in the fridge, minced garlic straight to the freezer."],
 exp:["싹이 나도 독은 아니지만 맛이 써져요 — 싹만 빼고 쓰면 됩니다.","Sprouts aren't toxic, just bitter — cut them out and use the rest."],
 bad:["쭈글쭈글 마르거나 곰팡이, 누런 진물이 보이면 버리세요.","Discard if shriveled, moldy, or weeping yellow."],
 fzt:["다진 마늘을 큐브틀에 얼려 하나씩 꺼내 쓰면 최고예요.","Freeze minced garlic in ice-cube trays — pop one out per dish."]},
{id:"감자",ko:"감자",en:"Potato",e:"🥔",g:"veg",rt:[2,4,"w"],fr:null,fz:null,
 tip:["빛을 완전히 차단한 서늘한 곳에 사과 한 알과 함께 두면 싹이 늦게 나요. 냉장하면 전분이 당으로 변해 맛이 떨어져요.","Keep in total darkness, cool, with an apple to slow sprouting. Fridges turn the starch sweet — skip them."],
 exp:["초록빛이 돌거나 싹이 많이 난 감자는 솔라닌 때문에 도려내도 아깝지 않게 버리는 게 안전해요.","Green-tinged or heavily sprouted potatoes carry solanine — safest to toss, not trim."],
 bad:["초록색 변색, 무른 부분, 시큼한 냄새가 상함 신호예요.","Green patches, soft spots and a sour smell are the signs."],
 fzt:["생감자 냉동은 스펀지가 돼요. 익혀 으깬 매시드포테이토 상태로만 1~2개월 냉동하세요.","Raw potatoes freeze into sponge. Only mash them cooked first — 1–2 months."]},
{id:"고구마",ko:"고구마",en:"Sweet Potato",e:"🍠",g:"veg",rt:[2,4,"w"],fr:null,fz:null,
 tip:["신문지에 싸서 13도 안팎 서늘한 곳에. 냉장고에선 냉해를 입어 속이 검게 변해요.","Wrap in paper, keep around 13°C. The fridge chills them into black-hearted ruin."],
 exp:["단단하고 진물 없으면 몇 주는 거뜬해요 — 상태가 곧 기한이에요.","Firm and dry means weeks of life — condition is the date."],
 bad:["끝이 물러지거나 검은 반점, 곰팡이 냄새가 나면 버리세요.","Toss when the ends soften or black spots and musty smells appear."],
 fzt:["생것은 비권장, 쪄서 으깨거나 슬라이스한 군고구마는 1~2개월 냉동 가능해요.","Skip raw; steamed-and-mashed or baked slices freeze fine for 1–2 months."]},
{id:"당근",ko:"당근",en:"Carrot",e:"🥕",g:"veg",rt:[3,5,"d"],fr:[2,3,"w"],fz:[8,12,"M"],
 tip:["흙당근이 더 오래가요. 잎을 잘라내고 키친타월에 싸서 냉장 야채칸에 세워 보관하세요.","Unwashed keeps longest. Cut the tops, wrap in paper towel, store upright in the crisper."],
 exp:["휘어지거나 살짝 마른 건 찬물에 담그면 살아나요 — 아직 버릴 때가 아니에요.","Bendy or dried-out carrots revive in cold water — not trash yet."],
 bad:["표면이 미끌거리거나 흰 곰팡이, 검게 무른 부분이 생기면 버리세요.","Slimy skin, white mold or black mush means goodbye."],
 fzt:["데쳐서 물기 빼고 소분 냉동하면 국·볶음용으로 1년 가까이 써요.","Blanch, dry, portion and freeze — nearly a year of soup-ready carrots."]},
{id:"오이",ko:"오이",en:"Cucumber",e:"🥒",g:"veg",rt:[1,2,"d"],fr:[7,null,"d"],fz:null,
 tip:["키친타월로 싼 뒤 지퍼백에 넣어 야채칸에. 물기가 닿으면 그 자리부터 물러져요.","Paper towel, then zip bag, then crisper. Wherever water touches, rot starts."],
 exp:["꼭지 쪽부터 무르니 꼭지 반대쪽부터 먹는 것도 요령이에요.","They soften from the stem end — eat from the other end first."],
 bad:["표면이 미끌거리고 누런빛이 돌며 시큼한 냄새가 나면 버리세요.","Slimy, yellowing and sour-smelling means done."],
 fzt:["수분 96%라 얼리면 흐물흐물 — 냉동은 비권장이에요. 남으면 피클이 답이에요.","96% water — freezing makes mush. Pickle the surplus instead."]},
{id:"애호박",ko:"애호박",en:"Zucchini",e:"🥒",g:"veg",rt:[2,3,"d"],fr:[1,2,"w"],fz:[3,null,"M"],
 tip:["랩이나 키친타월로 싸서 야채칸에. 씻지 말고 보관했다가 쓰기 직전에 씻으세요.","Wrap and crisper-drawer it; wash right before use, not before storage."],
 exp:["표면이 살짝 쭈글해도 속은 멀쩡한 경우가 많아요 — 잘라보고 판단하세요.","A wrinkly skin often hides fine flesh — cut and judge."],
 bad:["눌렀을 때 움푹 들어가고 진물이 나거나 곰팡이가 피면 버리세요.","Dents that stay, oozing or mold — discard."],
 fzt:["반달썰기해 소금 살짝 뿌려 물기 뺀 뒤 냉동하면 된장찌개용으로 3개월 가요.","Half-moon slices, lightly salted and drained, freeze 3 months for stews."]},
{id:"양배추",ko:"양배추",en:"Cabbage",e:"🥬",g:"veg",rt:[1,2,"d"],fr:[2,3,"w"],fz:[8,null,"M"],
 tip:["통째로는 심지를 도려내고 젖은 키친타월을 채워 랩핑하면 3주도 가요. 자른 단면은 랩으로 밀착.","Core it, stuff damp paper towel in the hole, wrap — three weeks easy. Press wrap onto cut faces."],
 exp:["겉잎이 시들면 한 겹 벗겨내고 쓰면 돼요 — 속은 새것이에요.","Wilted outer leaves peel away — the inside is still new."],
 bad:["단면이 검게 변하고 잎이 미끌거리거나 쿰쿰한 냄새가 나면 버리세요.","Blackened cuts, slimy leaves, musty smell — toss."],
 fzt:["채 썰어 데친 뒤 냉동하면 볶음·국용으로 8개월. 생 냉동은 숨이 죽어요.","Shred, blanch, freeze — 8 months for stir-fries; raw freezing wilts it."]},
{id:"상추",ko:"상추",en:"Lettuce",e:"🥗",g:"veg",rt:[1,null,"d"],fr:[7,10,"d"],fz:null,
 tip:["씻지 않은 채 키친타월과 번갈아 쌓아 밀폐용기에 — 물기 관리가 수명의 전부예요.","Unwashed, layered with paper towels in a sealed box — moisture control is everything."],
 exp:["가장자리가 갈변해도 그 부분만 떼면 먹을 수 있어요.","Browned edges tear away — the rest is fine."],
 bad:["잎이 녹아내리듯 물러지고 검은 물이 생기면 버리세요.","Leaves melting into dark liquid means it's over."],
 fzt:["얼리면 해동 순간 흐물 — 냉동 불가 채소의 대표예요.","Thaws into slime — the poster child of unfreezable greens."]},
{id:"시금치",ko:"시금치",en:"Spinach",e:"🍃",g:"veg",rt:[1,null,"d"],fr:[5,7,"d"],fz:[8,10,"M"],
 tip:["뿌리째 젖은 신문지에 싸서 세워 냉장하면 싱싱함이 오래가요.","Roots on, wrapped in damp paper, stored upright — freshness holds."],
 exp:["살짝 시든 건 찬물 목욕으로 복구돼요.","Slightly wilted? A cold-water bath brings it back."],
 bad:["잎이 검게 물러지고 쿰쿰한 냄새가 나면 버리세요.","Dark mushy leaves and a musty smell — discard."],
 fzt:["데쳐서 꽉 짜 한 줌씩 랩핑 냉동 — 국·나물용으로 8개월 이상 써요.","Blanch, squeeze, wrap in fist-sized portions — 8+ months for soups."]},
{id:"브로콜리",ko:"브로콜리",en:"Broccoli",e:"🥦",g:"veg",rt:[1,2,"d"],fr:[5,7,"d"],fz:[8,12,"M"],
 tip:["줄기를 아래로 세워 야채칸에. 꽃 부분에 물이 닿으면 금방 무너져요.","Store stem-down in the crisper; water on the florets starts the collapse."],
 exp:["꽃이 노래지기 시작하면 맛이 떨어질 뿐 먹을 수는 있어요 — 빨리 익혀 드세요.","Yellowing florets lose flavor, not safety — cook them soon."],
 bad:["꽃이 검게 변하고 물컹하거나 시큼한 냄새가 나면 버리세요.","Black mushy florets or a sour smell — toss."],
 fzt:["소금물에 데쳐 물기 빼고 냉동 — 1년 가까이 가는 모범 냉동 채소예요.","Blanch in salted water, dry, freeze — a model freezer vegetable, nearly a year."]},
{id:"파프리카",ko:"파프리카",en:"Bell Pepper",e:"🫑",g:"veg",rt:[2,3,"d"],fr:[1,2,"w"],fz:[6,null,"M"],
 tip:["물기 없이 하나씩 키친타월로 싸서 야채칸에. 자른 것은 씨를 빼고 밀폐하세요.","Dry, individually wrapped, in the crisper; deseed cut ones before sealing."],
 exp:["쭈글해져도 볶음용으론 충분해요 — 생식만 포기하면 됩니다.","Wrinkled peppers still stir-fry beautifully — just skip eating them raw."],
 bad:["꼭지에 곰팡이가 피거나 안쪽이 물러지면 버리세요.","Mold at the stem or a collapsing interior — discard."],
 fzt:["채 썰어 생으로 냉동해도 볶음용으론 문제없어요 — 6개월.","Slice and freeze raw — fine for cooking, 6 months."]},
{id:"토마토",ko:"토마토",en:"Tomato",e:"🍅",g:"veg",rt:[3,5,"d"],fr:[7,null,"d"],fz:[2,3,"M"],
 tip:["덜 익은 건 실온 후숙, 완숙은 꼭지를 아래로 두고 냉장. 냉장하면 향이 줄어드니 먹기 전 실온에 꺼내두세요.","Ripen underripe ones on the counter; refrigerate ripe ones stem-down, then re-warm before eating to revive aroma."],
 exp:["말랑해진 토마토는 소스·수프행 — 버릴 단계가 아니에요.","Soft tomatoes are sauce material, not trash."],
 bad:["껍질이 터지며 진물이 나오고 흰 곰팡이가 피면 버리세요.","Split skin weeping juice with white mold — toss."],
 fzt:["통째로 얼렸다 흐르는 물에 문지르면 껍질이 스르륵 — 소스용 냉동 꿀팁이에요.","Freeze whole, rub under water and the skin slips off — the sauce-maker's trick."]},
{id:"버섯",ko:"버섯",en:"Mushrooms",e:"🍄",g:"veg",rt:[1,null,"d"],fr:[5,7,"d"],fz:[8,null,"M"],
 tip:["비닐 대신 종이봉투에 — 숨을 쉬어야 안 물러져요. 절대 미리 씻지 마세요.","Paper bag, never plastic — they need to breathe. And never wash before storing."],
 exp:["갓이 살짝 마른 건 오히려 감칠맛이 진해져요.","A slightly dried cap actually deepens the umami."],
 bad:["표면이 끈적이고 검은 반점, 암모니아 같은 냄새가 나면 버리세요.","Sticky surface, dark spots, ammonia smell — done."],
 fzt:["생으로 찢어 냉동하면 감칠맛이 오히려 상승 — 국·볶음에 얼린 채 투하하세요.","Tear and freeze raw — umami rises. Drop in frozen, straight into the pan."]},
{id:"대파",ko:"대파",en:"Green Onion",e:"🌱",g:"veg",rt:[2,3,"d"],fr:[1,2,"w"],fz:[3,null,"M"],
 tip:["뿌리째 신문지에 싸서 세워 보관, 또는 손질 후 키친타월 깐 밀폐용기에.","Roots on, wrapped upright in paper — or trimmed into a paper-lined sealed box."],
 exp:["겉잎이 마르면 벗겨내세요 — 속대는 여전히 팔팔해요.","Peel the dried outer layer — the core is still lively."],
 bad:["미끌거리는 진액과 무른 줄기, 시큼한 냄새가 상함 신호예요.","Slime, soft stalks and sourness are the signs."],
 fzt:["송송 썰어 냉동실 전용 파 통에 — 한국 냉장고의 국룰, 3개월.","Chop and keep a dedicated freezer tub — the Korean fridge standard, 3 months."]},
{id:"무",ko:"무",en:"Radish",e:"⚪",g:"veg",rt:[5,7,"d"],fr:[2,4,"w"],fz:[1,null,"M"],
 tip:["잎을 잘라내야 수분을 안 뺏겨요. 신문지에 싸서 냉장 야채칸에.","Cut the greens — they steal moisture. Wrap in paper for the crisper."],
 exp:["바람 든 무(속에 구멍)는 국물용으론 여전히 훌륭해요.","A spongy core still makes excellent broth."],
 bad:["속이 검게 변하거나 표면이 미끌거리면 버리세요.","Blackened core or slimy skin — toss."],
 fzt:["나박·채썰기해 냉동하면 국물용 1개월 — 생채용은 포기하세요.","Cube or shred for broth, 1 month frozen — raw salads are off the table."]},
{id:"깻잎",ko:"깻잎",en:"Perilla Leaves",e:"🌿",g:"veg",rt:[1,null,"d"],fr:[5,7,"d"],fz:null,
 tip:["젖은 키친타월에 싸서 밀폐용기에 세워두면 일주일 싱싱해요. 물컵에 꽂아 냉장하는 것도 요령.","Damp paper towel, sealed box, stored upright — or stand stems in a cup of water in the fridge."],
 exp:["가장자리부터 마르니 마른 잎만 골라내며 쓰세요.","They dry from the edges — pick out the crisp ones as you go."],
 bad:["검은 반점이 번지고 잎이 물러지면 버리세요.","Spreading black spots and softened leaves — done."],
 fzt:["얼리면 특유의 향이 날아가요 — 남으면 깻잎장아찌가 정답이에요.","Freezing kills the aroma — pickle the leftovers instead."]},
{id:"콩나물",ko:"콩나물",en:"Bean Sprouts",e:"🌱",g:"veg",rt:null,fr:[2,3,"d"],fz:null,
 tip:["물에 잠기게 담아 냉장하고 물을 매일 갈아주면 3일까지 아삭해요.","Submerge in water in the fridge, change daily — crisp for three days."],
 exp:["콩나물은 산 날 요리하는 게 기본 — 기한보다 회전이 답이에요.","Sprouts are a buy-today-cook-today food — rotation beats dates."],
 bad:["줄기가 미끌거리고 비린내가 올라오면 버리세요.","Slimy stems and a fishy whiff — discard."],
 fzt:["얼리면 아삭함이 전멸해요. 데쳐서 무침으로 만들어 냉장하는 게 나아요.","Freezing kills the crunch entirely — blanch and dress them instead."]},
{id:"배추",ko:"배추",en:"Napa Cabbage",e:"🥬",g:"veg",rt:[3,5,"d"],fr:[2,3,"w"],fz:null,
 tip:["신문지에 싸서 뿌리가 아래로 가게 세워 서늘한 곳 또는 냉장 보관하세요.","Wrap in paper, store upright root-down, cool room or fridge."],
 exp:["겉잎 몇 장이 시들해도 속잎은 몇 주를 버텨요.","Outer leaves wilt; inner leaves hold for weeks."],
 bad:["줄기가 반투명하게 물러지고 쿰쿰한 냄새가 나면 버리세요.","Translucent mushy ribs and a musty smell — toss."],
 fzt:["냉동보단 소금에 절이는 게 조상님의 답 — 김치가 곧 배추의 저장법이에요.","The ancestors' answer beats the freezer — kimchi is napa's storage method."]},
{id:"옥수수",ko:"옥수수",en:"Corn",e:"🌽",g:"veg",rt:[1,null,"d"],fr:[1,3,"d"],fz:[8,12,"M"],
 tip:["수확 순간부터 당이 전분으로 변해요 — 껍질째 냉장하고 최대한 빨리 드세요.","Sugar turns to starch from the moment of harvest — refrigerate in husk, eat fast."],
 exp:["산 날 먹는 옥수수가 제일 달아요. 기한은 사실상 '당도 유통기한'이에요.","Day-one corn is the sweetest — the real expiry is sweetness."],
 bad:["알갱이가 움푹 꺼지고 시큼한 냄새, 끈적임이 생기면 버리세요.","Sunken kernels, sourness, stickiness — discard."],
 fzt:["쪄서 알을 발라내거나 통째로 랩핑 냉동 — 1년 내내 여름 맛이에요.","Steam, then freeze kernels or whole cobs wrapped — summer all year."]},
/* ---- 과일 fruit (18) ---- */
{id:"사과",ko:"사과",en:"Apple",e:"🍎",g:"fruit",rt:[5,7,"d"],fr:[4,6,"w"],fz:[8,null,"M"],
 tip:["하나씩 랩이나 봉지에 싸서 냉장 — 사과의 에틸렌이 다른 과일·채소를 익혀버려요.","Bag them individually in the fridge — apple ethylene fast-forwards everything nearby."],
 exp:["쭈글해진 사과는 껍질을 벗겨 잼·조림으로 — 맛은 그대로예요.","Wrinkled apples peel into perfect jam — the flavor stays."],
 bad:["갈색 반점이 물러지며 퍼지고 발효 냄새가 나면 버리세요.","Spreading soft brown patches and a fermented smell — toss."],
 fzt:["슬라이스에 레몬즙 뿌려 냉동하면 8개월 — 스무디·파이용이에요.","Slices with lemon juice freeze 8 months — for smoothies and pies."]},
{id:"바나나",ko:"바나나",en:"Banana",e:"🍌",g:"fruit",rt:[2,5,"d"],fr:[5,7,"d"],fz:[2,3,"M"],
 tip:["꼭지를 랩으로 감으면 후숙이 늦어져요. 익은 뒤엔 냉장 — 껍질만 검어지고 속은 멀쩡해요.","Wrap the crown to slow ripening. Refrigerate once ripe — the peel blackens, the fruit doesn't."],
 exp:["검은 반점 바나나가 가장 달아요 — '상함'이 아니라 '완성'이에요.","Spotted bananas are peak sweetness — that's completion, not decay."],
 bad:["껍질이 아니라 속이 검게 물러지고 시큼한 술 냄새가 나면 버리세요.","When the flesh itself is dark, mushy and boozy — discard."],
 fzt:["껍질 벗겨 통째 냉동 — 스무디와 바나나 아이스크림의 원료가 돼요.","Peel and freeze whole — raw material for smoothies and nice-cream."]},
{id:"포도",ko:"포도",en:"Grapes",e:"🍇",g:"fruit",rt:[2,3,"d"],fr:[1,2,"w"],fz:[3,5,"M"],
 tip:["씻지 말고 종이타월 깐 용기에 담아 냉장 — 하얀 가루(과분)는 신선함의 증거니 닦지 마세요.","Store unwashed on paper towel; the white bloom is a freshness badge — don't wipe it."],
 exp:["알이 몇 개 물렀다고 송이를 버리지 마세요 — 무른 알만 골라내면 돼요.","A few soft berries don't condemn the bunch — pick them out."],
 bad:["줄기 쪽부터 곰팡이가 피고 알이 쭈그러들며 시큼해지면 버리세요.","Mold at the stems, shriveling, sourness — done."],
 fzt:["알알이 떼어 냉동하면 여름 천연 셔벗 — 얼린 채로 먹어요.","Freeze individual berries — nature's sorbet, eaten still frozen."]},
{id:"딸기",ko:"딸기",en:"Strawberries",e:"🍓",g:"fruit",rt:[1,null,"d"],fr:[3,5,"d"],fz:[8,12,"M"],
 tip:["절대 미리 씻지 말고, 겹치지 않게 키친타월 위에 한 층으로 — 딸기는 눌린 자리부터 상해요.","Never pre-wash; single layer on paper towel — bruised spots are where rot begins."],
 exp:["딸기는 3일의 과일이에요. 못 먹을 것 같으면 이틀째에 잼을 결심하세요.","Strawberries live on a 3-day clock — commit to jam by day two."],
 bad:["흰 솜 곰팡이 하나가 보이면 닿아 있던 주변까지 같이 버리세요.","One cottony mold spot condemns its neighbors too."],
 fzt:["꼭지 떼고 통째 냉동 — 스무디·잼용 1년, 생식감은 사라져요.","Hull and freeze whole — a year for smoothies and jam; fresh texture is gone."]},
{id:"블루베리",ko:"블루베리",en:"Blueberries",e:"🫐",g:"fruit",rt:[2,3,"d"],fr:[1,2,"w"],fz:[10,12,"M"],
 tip:["씻지 않고 통풍되는 용기째 냉장 — 물기가 곰팡이의 초대장이에요.","Unwashed, ventilated container, fridge — moisture is mold's invitation."],
 exp:["쭈글해진 알은 요거트·오트밀 토핑으로 아직 훌륭해요.","Wrinkled berries still crown yogurt and oatmeal well."],
 bad:["뭉개진 알에서 즙이 새고 흰 곰팡이가 보이면 그 주변째 버리세요.","Leaking crushed berries with white fuzz — toss them and their neighbors."],
 fzt:["냉동 최적화 과일 1위 — 씻어 말려 얼리면 1년, 얼린 채 요리에 바로 써요.","The most freezer-friendly fruit — wash, dry, freeze for a year, use straight from frozen."]},
{id:"수박",ko:"수박",en:"Watermelon",e:"🍉",g:"fruit",rt:[7,10,"d"],fr:[3,4,"d"],fz:[2,null,"M"],
 tip:["통수박은 서늘한 실온이 오히려 낫고, 자른 뒤엔 단면을 랩으로 밀착해 냉장 — 3~4일이 한계예요.","Whole melons prefer cool room temp; once cut, press-wrap the face and refrigerate — 3–4 days max."],
 exp:["자른 수박은 여름철 식중독 단골 — 기한보다 '자른 시점'을 기억하세요.","Cut watermelon is a summer food-poisoning regular — track the cut date, not the label."],
 bad:["과육이 스펀지처럼 퍼석해지고 시큼한 냄새가 나면 버리세요.","Spongy grainy flesh and a sour smell — discard."],
 fzt:["큐브로 얼려 갈면 수박주스·슬러시 — 생식감은 포기예요.","Freeze cubes for juice and slush — fresh crunch not included."]},
{id:"참외",ko:"참외",en:"Korean Melon",e:"🍈",g:"fruit",rt:[4,7,"d"],fr:[7,10,"d"],fz:null,
 tip:["햇빛 없는 실온에서 향이 올라오면 그때 냉장 — 너무 차게 오래 두면 향이 죽어요.","Let the aroma bloom at room temp, then chill — long cold storage mutes it."],
 exp:["배꼽이 클수록 잘 익은 참외 — 익은 것부터 드세요.","A big blossom scar means ripeness — eat those first."],
 bad:["배꼽 주변이 물러지고 발효 냄새가 나면 버리세요.","Softness around the scar and a fermented smell — toss."],
 fzt:["얼리면 수분이 빠져 스펀지가 돼요 — 냉동 비권장.","Freezing drains it into sponge — not recommended."]},
{id:"복숭아",ko:"복숭아",en:"Peach",e:"🍑",g:"fruit",rt:[2,3,"d"],fr:[3,5,"d"],fz:[2,3,"M"],
 tip:["딱딱하면 실온 후숙, 향이 나면 바로 냉장 — 복숭아는 눌린 자리부터 하루 만에 상해요.","Ripen hard ones on the counter; refrigerate at first fragrance. Bruises turn overnight."],
 exp:["복숭아는 기다려주지 않는 과일 — 향이 절정일 때가 데드라인이에요.","Peaches wait for no one — peak fragrance is the deadline."],
 bad:["씨 주변이 갈색으로 물러지고 진물이 나면 버리세요.","Brown mush around the pit and weeping juice — done."],
 fzt:["껍질 벗겨 조각내 설탕 살짝 뿌려 냉동 — 스무디용 2~3개월.","Peel, slice, dust with sugar, freeze — 2–3 months of smoothie stock."]},
{id:"감",ko:"감",en:"Persimmon",e:"🟠",g:"fruit",rt:[3,5,"d"],fr:[1,2,"w"],fz:[2,3,"M"],
 tip:["단감은 냉장, 덜 익은 떫은 감은 실온에서 홍시로 후숙시키세요.","Chill sweet persimmons; leave astringent ones out to ripen into hongsi."],
 exp:["물러진 감은 상한 게 아니라 홍시가 된 것 — 숟가락으로 떠먹는 디저트예요.","A softened persimmon isn't spoiled, it's hongsi — a spoon dessert."],
 bad:["껍질이 터지고 시큼한 술 냄새, 곰팡이가 보이면 버리세요.","Split skin, boozy sourness, mold — that's actual spoilage."],
 fzt:["홍시를 통째 얼리면 여름의 감 셔벗 — 반해동해 떠먹어요.","Freeze whole hongsi — half-thaw and spoon it like sorbet."]},
{id:"배",ko:"배",en:"Korean Pear",e:"🍐",g:"fruit",rt:[3,5,"d"],fr:[2,4,"w"],fz:null,
 tip:["하나씩 신문지에 싸서 냉장 — 서로 닿은 자리부터 무르기 시작해요.","Wrap individually in paper for the fridge — contact points soften first."],
 exp:["묵직하고 단단하면 한 달도 가는 저장 과일이에요.","Heavy and firm means a month of life — a natural keeper."],
 bad:["껍질이 쭈글해지며 속이 갈변하고 발효 냄새가 나면 버리세요.","Wrinkling skin, browning core, fermented smell — toss."],
 fzt:["얼리면 배 특유의 아삭함이 사라져요 — 갈아서 고기 재울 때 쓰는 게 낫죠.","Freezing kills the signature crunch — grate it into marinade instead."]},
{id:"귤",ko:"귤",en:"Tangerine",e:"🍊",g:"fruit",rt:[7,null,"d"],fr:[2,3,"w"],fz:null,
 tip:["박스째 두지 말고 꺼내 펼쳐두세요 — 귤 하나가 곰팡이면 박스 전체가 위험해요.","Never leave them boxed — spread them out; one moldy tangerine takes the crate down."],
 exp:["말랑해진 귤이 더 단 경우도 많아요 — 곰팡이만 없다면 괜찮아요.","Softer tangerines are often sweeter — mold-free means fine."],
 bad:["흰색·초록색 곰팡이가 피면 닿아 있던 귤까지 확인하고 버리세요.","White-green mold means checking every neighbor it touched."],
 fzt:["얼리면 쓴맛이 올라와요 — 냉동 비권장, 대신 청귤청·잼으로.","Freezing draws out bitterness — make syrup or jam instead."]},
{id:"오렌지",ko:"오렌지",en:"Orange",e:"🍊",g:"fruit",rt:[7,null,"d"],fr:[3,4,"w"],fz:null,
 tip:["실온 일주일, 그 이상은 야채칸에 — 껍질이 두꺼워 귤보다 잘 버텨요.","A week on the counter, then the crisper — that thick peel buys time."],
 exp:["가벼워진 오렌지는 수분이 빠진 것 — 주스로 마지막을 장식해주세요.","A light orange has dried inside — send it off as juice."],
 bad:["껍질이 물러지며 곰팡이가 피고 발효 냄새가 나면 버리세요.","Softening peel with mold and ferment — discard."],
 fzt:["통째 냉동은 비권장 — 즙만 짜서 얼음틀에 얼리면 요리용으로 훌륭해요.","Skip whole freezing — juice into ice-cube trays is the move."]},
{id:"레몬",ko:"레몬",en:"Lemon",e:"🍋",g:"fruit",rt:[7,null,"d"],fr:[3,4,"w"],fz:[3,4,"M"],
 tip:["지퍼백에 밀봉해 냉장하면 한 달 — 그냥 두면 일주일 만에 딱딱해져요.","Zip-bagged in the fridge lasts a month; naked on the counter, it hardens in a week."],
 exp:["딱딱해진 레몬도 전자레인지 10초면 즙이 다시 잘 나와요.","A hardened lemon juices again after 10 seconds in the microwave."],
 bad:["말랑한 반점이 생기고 흰 곰팡이가 피면 버리세요.","Soft spots and white mold — toss."],
 fzt:["슬라이스·즙·제스트로 나눠 냉동하면 버릴 게 없어요 — 3~4개월.","Freeze as slices, juice and zest — zero waste, 3–4 months."]},
{id:"키위",ko:"키위",en:"Kiwi",e:"🥝",g:"fruit",rt:[3,5,"d"],fr:[1,2,"w"],fz:[1,2,"M"],
 tip:["딱딱하면 사과와 한 봉지에 넣어 후숙 — 하루 만에 말랑해져요. 익은 건 냉장.","Ripen hard ones bagged with an apple — soft in a day. Then refrigerate."],
 exp:["살짝 눌렀을 때 탄력 있게 들어가면 최적기예요.","A gentle give under the thumb is peak time."],
 bad:["껍질이 쭈글해지며 시큼한 술 냄새와 진물이 나면 버리세요.","Wrinkling with boozy smell and ooze — done."],
 fzt:["껍질 벗겨 슬라이스 냉동 — 스무디용 1~2개월, 생식감은 사라져요.","Peel, slice, freeze — 1–2 months for smoothies; fresh texture lost."]},
{id:"망고",ko:"망고",en:"Mango",e:"🥭",g:"fruit",rt:[2,5,"d"],fr:[5,7,"d"],fz:[6,null,"M"],
 tip:["향이 나고 살짝 말랑해질 때까지 실온 후숙, 그다음 냉장하세요.","Ripen at room temp until fragrant and slightly soft, then chill."],
 exp:["검은 반점이 몇 개 생겨도 속은 괜찮은 경우가 많아요 — 잘라서 확인하세요.","A few black freckles rarely reach the flesh — cut and check."],
 bad:["껍질이 움푹 꺼지고 신 냄새와 회색 섬유질이 보이면 버리세요.","Caving skin, sour smell, gray fibers — toss."],
 fzt:["깍둑 썰어 냉동하면 6개월 — 망고빙수·스무디가 상시 대기 상태가 돼요.","Cube and freeze for 6 months — mango bingsu on standby."]},
{id:"파인애플",ko:"파인애플",en:"Pineapple",e:"🍍",g:"fruit",rt:[1,2,"d"],fr:[3,5,"d"],fz:[6,null,"M"],
 tip:["파인애플은 수확 후 더 익지 않아요 — 산 날이 가장 맛있는 날, 자르면 밀폐 냉장하세요.","Pineapples never ripen after harvest — purchase day is peak day. Once cut, sealed and chilled."],
 exp:["자른 뒤 3~5일이 한계 — 시큼해지기 전에 구워 먹는 것도 방법이에요.","3–5 days once cut — grill the stragglers before they sour."],
 bad:["과육이 갈변하며 발효 냄새가 나고 진물이 생기면 버리세요.","Browning flesh, fermented smell, ooze — discard."],
 fzt:["조각 냉동 6개월 — 다만 생파인애플 효소는 얼려도 살아 있으니 젤라틴 요리엔 못 써요.","Cubes freeze 6 months — note the enzyme survives freezing, so still no gelatin desserts."]},
{id:"아보카도",ko:"아보카도",en:"Avocado",e:"🥑",g:"fruit",rt:[2,4,"d"],fr:[3,5,"d"],fz:[3,4,"M"],
 tip:["꼭지가 쏙 빠지고 초록빛이면 완숙 — 그때 냉장으로 시간을 멈추세요. 자른 건 씨를 붙인 채 랩핑.","Ripe when the stem pops off green — then refrigerate to pause time. Wrap cut halves with the pit in."],
 exp:["아보카도의 완숙 타이밍은 몇 시간 단위 — 하루 두 번 확인하는 과일이에요.","Avocado ripeness moves in hours — a check-twice-a-day fruit."],
 bad:["과육 전체가 갈색·검은색이고 쿰쿰한 냄새가 나면 버리세요. 갈변 몇 줄은 괜찮아요.","Fully brown-black flesh with musty smell — toss. A few brown streaks are fine."],
 fzt:["으깨서 레몬즙 섞어 냉동 — 과카몰리용 3~4개월, 슬라이스용은 포기하세요.","Mash with lemon juice and freeze — 3–4 months for guacamole; slices don't survive."]},
{id:"체리",ko:"체리",en:"Cherries",e:"🍒",g:"fruit",rt:[1,2,"d"],fr:[4,7,"d"],fz:[6,null,"M"],
 tip:["씻지 않고 꼭지째 밀폐용기에 냉장 — 체리는 상온에서 하루가 냉장 하루치와 같아요.","Unwashed, stems on, sealed in the fridge — one counter day costs a fridge day."],
 exp:["꼭지가 초록색이고 탱탱하면 신선 — 꼭지 마른 것부터 드세요.","Green springy stems mean fresh — eat the dry-stemmed ones first."],
 bad:["쭈글해지고 즙이 새며 곰팡이가 피면 버리세요.","Shriveling, leaking, molding — done."],
 fzt:["씨 빼고 냉동하면 6개월 — 얼린 채 먹어도 별미예요.","Pit and freeze for 6 months — delicious eaten still frozen."]},
/* ---- 육류 meat (12) ---- */
{id:"소고기",ko:"소고기 (생)",en:"Beef (raw)",e:"🥩",g:"meat",rt:null,fr:[3,5,"d"],fz:[6,12,"M"],
 tip:["냉장고 가장 찬 안쪽 칸에 원래 포장 그대로 — 육즙(드립)이 다른 식품에 닿지 않게 맨 아래 칸에 두세요.","Coldest back shelf, original wrap, bottom rack — drip must never touch other food."],
 exp:["표면이 갈색으로 변하는 건 산소 접촉 때문일 수 있어요 — 냄새가 정상이면 대부분 괜찮아요.","Surface browning is often just oxygen — if it smells normal, it usually is."],
 bad:["시큼하거나 암모니아 냄새, 미끌거리는 표면, 초록빛이 돌면 버리세요.","Sour or ammonia smell, slimy surface, greenish tint — discard."],
 fzt:["1회분씩 랩+지퍼백 이중 포장으로 냉동 — 해동은 냉장실에서 하루가 정석이에요.","Double-wrap single portions; the correct thaw is overnight in the fridge."]},
{id:"돼지고기",ko:"돼지고기 (생)",en:"Pork (raw)",e:"🐖",g:"meat",rt:null,fr:[3,5,"d"],fz:[4,6,"M"],
 tip:["구입 즉시 냉장 최하단 — 이틀 내 안 먹을 분량은 바로 소분 냉동하세요.","Bottom shelf on arrival; portion and freeze anything you won't cook in two days."],
 exp:["포장 팽창은 세균 가스일 수 있어요 — 부풀어 있으면 기한과 무관하게 버리세요.","A puffed package can be bacterial gas — toss regardless of the date."],
 bad:["회색빛 변색, 시큼한 냄새, 끈적한 표면이 상함 신호예요.","Gray tint, sour smell, tacky surface — the signs."],
 fzt:["지방이 소고기보다 빨리 산패해요 — 냉동 4~6개월 내 소진이 목표예요.","Pork fat goes rancid faster than beef — aim to finish within 4–6 months frozen."]},
{id:"닭고기",ko:"닭고기 (생)",en:"Chicken (raw)",e:"🍗",g:"meat",rt:null,fr:[1,2,"d"],fz:[9,12,"M"],
 tip:["생닭은 냉장 1~2일이 전부 — 씻지 말고 바로 조리하세요, 씻는 물이 캄필로박터를 사방에 튀깁니다.","Raw chicken gets 1–2 fridge days. Don't rinse it — the splash sprays campylobacter everywhere."],
 exp:["육류 중 가장 짧은 기한 — 산 날 요리하거나 산 날 얼리세요.","The shortest clock in the meat aisle — cook it or freeze it the day you buy."],
 bad:["회색·초록빛, 시큼한 냄새, 만졌을 때 미끈한 점액이 있으면 버리세요.","Gray-green tint, sourness, slick slime — toss."],
 fzt:["부위별 소분 후 냉동 9~12개월 — 해동은 냉장실, 실온 해동은 금지예요.","Portion by cut, freeze 9–12 months — thaw in the fridge, never on the counter."]},
{id:"다진고기",ko:"다진 고기",en:"Ground Meat",e:"🥩",g:"meat",rt:null,fr:[1,2,"d"],fz:[3,4,"M"],
 tip:["표면적이 넓어 세균이 가장 빨리 붙는 형태예요 — 냉장은 하루 이틀, 그 이상은 무조건 냉동.","Maximum surface area means fastest spoilage — two fridge days max, freezer beyond that."],
 exp:["덩어리 고기보다 기한이 절반이라고 기억하세요.","Remember: half the shelf life of whole cuts."],
 bad:["속까지 갈변하고 시큼한 냄새, 끈적임이 있으면 버리세요.","Browning through the middle, sourness, tackiness — done."],
 fzt:["납작하게 펴서 냉동하면 해동이 10배 빨라요 — 지퍼백 필사 냉동법이에요.","Freeze flattened in zip bags — thaws ten times faster."]},
{id:"삼겹살",ko:"삼겹살",en:"Pork Belly",e:"🥓",g:"meat",rt:null,fr:[2,3,"d"],fz:[3,4,"M"],
 tip:["기름이 많아 산패가 빠른 부위 — 냉장 2~3일, 구울 계획 없으면 바로 냉동하세요.","All that fat oxidizes fast — 2–3 fridge days, freeze immediately if no grill plan."],
 exp:["색이 짙어지고 기름 부분이 노래지면 신선도가 꺾인 거예요.","Darkening meat and yellowing fat mean freshness has turned."],
 bad:["기름에서 쩐내(산패취)가 나고 표면이 미끌거리면 버리세요.","Rancid-smelling fat and slime — toss."],
 fzt:["구이용은 1회분씩 랩핑 — 얼린 채 겹쳐두면 다신 안 떨어져요.","Wrap grill portions separately — frozen slabs stacked bare never come apart again."]},
{id:"베이컨",ko:"베이컨",en:"Bacon",e:"🥓",g:"meat",rt:null,fr:[5,7,"d"],fz:[1,null,"M"],
 tip:["개봉 후엔 랩으로 단면을 밀착해 냉장 — 공기가 산패의 주범이에요.","Once opened, press-wrap the exposed face — air drives the rancidity."],
 exp:["미개봉은 표시 기한, 개봉 후엔 일주일이 실전 기한이에요.","Sealed goes by the label; opened, a week is the real number."],
 bad:["갈색·회색 변색과 쩐내, 미끈거림이 상함 신호예요.","Brown-gray fading, rancid smell, slickness — the signs."],
 fzt:["몇 장씩 유산지 사이에 끼워 냉동하면 필요한 만큼만 떼어 써요.","Freeze in small stacks with parchment between — peel off just what you need."]},
{id:"햄",ko:"햄 (슬라이스)",en:"Ham (sliced)",e:"🍖",g:"meat",rt:null,fr:[3,5,"d"],fz:[1,2,"M"],
 tip:["개봉하면 밀폐용기로 옮기고 3~5일 내 소진 — 슬라이스 햄은 겉보기보다 빨리 상해요.","Transfer to a sealed box on opening; 3–5 days — sliced ham turns faster than it looks."],
 exp:["가공육도 개봉하는 순간 기한 시계가 리셋돼요 — 라벨 날짜는 미개봉 기준이에요.","Opening resets the clock — the label date assumes a sealed pack."],
 bad:["표면이 무지개빛으로 번들거리는 건 괜찮지만, 끈적이고 시큼하면 버리세요.","Iridescent sheen is harmless; sticky and sour is not."],
 fzt:["몇 장씩 소분 냉동 1~2개월 — 해동 후 식감은 볶음·찌개용이에요.","Freeze in small bundles, 1–2 months — post-thaw texture suits frying and stew."]},
{id:"소시지",ko:"소시지",en:"Sausage",e:"🌭",g:"meat",rt:null,fr:[7,null,"d"],fz:[1,2,"M"],
 tip:["개봉 후 밀폐해 냉장 일주일 — 진공포장 미개봉은 라벨 기한까지 안심이에요.","Sealed after opening, one fridge week; unopened vacuum packs ride the label."],
 exp:["표면이 마르는 건 괜찮지만 진물이 나오면 경계 신호예요.","Drying is fine; weeping liquid is the warning."],
 bad:["시큼한 냄새, 미끈한 점액, 색 변화가 함께 오면 버리세요.","Sourness, slime and color change together — toss."],
 fzt:["칼집 내기 전 통째로 냉동 — 얼린 채 끓는 물에 바로 데쳐도 돼요.","Freeze whole, uncut — they can go straight from freezer to boiling water."]},
{id:"양념육",ko:"양념육",en:"Marinated Meat",e:"🍖",g:"meat",rt:null,fr:[1,2,"d"],fz:[2,3,"M"],
 tip:["양념이 상함을 가려요 — 눈·코로 판별이 어려우니 기한을 더 보수적으로 잡으세요.","Marinade masks spoilage — your eyes and nose get fooled, so cut the timeline shorter."],
 exp:["양념됐다고 오래가는 게 아니에요 — 오히려 냉장 1~2일로 생고기보다 짧게 봐야 해요.","Marinade doesn't preserve — treat it as shorter-lived than plain meat: 1–2 days."],
 bad:["양념 위로 거품이 올라오거나 시큼한 발효취가 나면 버리세요.","Bubbles rising through the sauce or a fermented tang — discard."],
 fzt:["양념째 지퍼백에 납작 냉동 — 해동하면서 재워져 오히려 맛있어져요.","Freeze flat in the marinade — it seasons itself as it thaws."]},
{id:"익힌고기",ko:"익힌 고기",en:"Cooked Meat",e:"🍖",g:"meat",rt:null,fr:[3,4,"d"],fz:[2,3,"M"],
 tip:["실온 2시간이 마지노선 — 식으면 바로 밀폐해 냉장하세요. 여름엔 1시간이에요.","Two hours at room temp is the line — one in summer. Seal and chill once cooled."],
 exp:["냉장 3~4일 안에 못 먹을 것 같으면 첫날 바로 냉동하는 게 맛도 좋아요.","If four fridge days won't cover it, freeze on day one — the flavor thanks you."],
 bad:["표면이 미끈해지고 쉰내가 나면 재가열해도 소용없어요 — 버리세요.","Slick surface and a sour smell — reheating won't save it. Toss."],
 fzt:["국물 요리는 국물째, 구이는 슬라이스로 소분 냉동하세요.","Freeze braises in their liquid, roasts in slices."]},
{id:"장조림",ko:"장조림",en:"Soy-braised Beef",e:"🥢",g:"meat",rt:null,fr:[1,2,"w"],fz:[2,3,"M"],
 tip:["간장 국물에 잠긴 상태로 밀폐 냉장 — 국물이 방부 역할을 해요. 덜어 먹을 땐 마른 수저로.","Keep the meat submerged in its soy broth, sealed — and always use a dry spoon."],
 exp:["국물에 잠긴 상태 기준 1~2주 — 국물 밖으로 나온 고기부터 상해요.","1–2 weeks while submerged — exposed meat spoils first."],
 bad:["국물 표면에 흰 막이나 거품, 시큼한 냄새가 생기면 버리세요.","White film or foam on the broth, sourness — done."],
 fzt:["국물째 소분 냉동 — 해동 후 한 번 끓여서 드세요.","Freeze in portions with broth — boil once after thawing."]},
{id:"육포",ko:"육포",en:"Beef Jerky",e:"🥓",g:"meat",rt:[1,2,"w"],fr:[1,2,"M"],fz:[6,null,"M"],
 tip:["개봉 후엔 지퍼백에 공기를 빼고 밀봉 — 건조식품이지만 습기를 먹으면 곰팡이가 펴요.","Squeeze the air out of a zip bag after opening — dried, yes, but humidity invites mold."],
 exp:["미개봉은 라벨 기한(수개월), 개봉 후 실온은 1~2주가 안전선이에요.","Sealed rides the label for months; opened, 1–2 weeks at room temp is the safe line."],
 bad:["흰 반점이 소금 결정인지 곰팡이인지 헷갈리면 — 냄새가 쿰쿰하면 곰팡이예요.","White specks: salt or mold? A musty smell settles the question."],
 fzt:["장기 보관은 냉동이 정답 — 6개월 이상, 꺼내서 바로 먹어도 딱딱하지 않아요.","For the long haul, freeze — 6+ months, and it's chewable straight out."]},
/* ---- 수산물 seafood (12) ---- */
{id:"생선",ko:"생선 (생물)",en:"Fresh Fish",e:"🐟",g:"seafood",rt:null,fr:[1,2,"d"],fz:[3,6,"M"],
 tip:["내장부터 상해요 — 산 날 손질(내장 제거)해서 키친타월로 감싸 냉장 최하단에.","Guts spoil first — clean it the day you buy, wrap in paper towel, coldest shelf."],
 exp:["생선의 냉장 기한은 사실상 '오늘 아니면 내일' — 이틀을 넘기지 마세요.","Fresh fish runs on a today-or-tomorrow clock — never past two days."],
 bad:["눈이 탁해지고 아가미가 갈색이며 비린내가 아니라 암모니아 냄새가 나면 버리세요.","Cloudy eyes, brown gills, ammonia instead of ocean — toss."],
 fzt:["흰살생선은 6개월, 고등어·연어 같은 기름진 생선은 3개월이 냉동 한계예요.","White fish keeps 6 months frozen; oily fish like mackerel, 3."]},
{id:"연어",ko:"연어 (생)",en:"Salmon (raw)",e:"🍣",g:"seafood",rt:null,fr:[1,2,"d"],fz:[2,3,"M"],
 tip:["얼음 위 보관이 이상적 — 밀폐용기 바닥에 얼음팩, 그 위에 키친타월, 그 위에 연어.","Ice-bed storage is ideal: ice pack, paper towel, salmon, in that order, sealed."],
 exp:["횟감은 당일, 구이용은 이틀 — 용도에 따라 기한이 달라요.","Sashimi-grade means today; for grilling, two days."],
 bad:["가장자리가 회색으로 변하고 살이 눌렀을 때 자국이 남으면 버리세요.","Graying edges and flesh that holds a fingerprint — done."],
 fzt:["기름이 많아 2~3개월이 한계 — 1회분씩 랩+지퍼백 이중 포장하세요.","That rich fat caps it at 2–3 months — double-wrap single portions."]},
{id:"고등어",ko:"고등어",en:"Mackerel",e:"🐟",g:"seafood",rt:null,fr:[1,2,"d"],fz:[2,3,"M"],
 tip:["등푸른 생선은 히스타민이 빨리 생겨요 — 구입 즉시 냉장, 하루 이틀 내 조리하세요.","Blue-backed fish build histamine fast — chill on arrival, cook within a day or two."],
 exp:["고등어 식중독(히스타민 중독)은 상한 냄새가 안 나도 생길 수 있어요 — 기한을 지키는 게 답이에요.","Histamine poisoning can strike without a bad smell — the timeline is the only defense."],
 bad:["살이 흐물해지고 껍질 광택이 사라지며 신 냄새가 나면 버리세요.","Mushy flesh, dulled skin, sour smell — toss."],
 fzt:["손질 후 소분 냉동 2~3개월 — 자반(염장)이면 조금 더 갑니다.","Cleaned and portioned, 2–3 months — salted mackerel stretches a bit longer."]},
{id:"새우",ko:"새우",en:"Shrimp",e:"🦐",g:"seafood",rt:null,fr:[1,2,"d"],fz:[6,12,"M"],
 tip:["머리부터 상하니 장기 보관이면 머리를 떼고 — 냉장은 이틀, 그 이상은 냉동이에요.","The head spoils first — remove it for keeping. Two fridge days, then the freezer."],
 exp:["검게 변한 머리(흑변)는 산화 현상으로 맛 문제일 뿐 — 냄새가 정상이면 먹어도 돼요.","Blackened heads are oxidation, a looks issue — fine if the smell is clean."],
 bad:["암모니아 냄새와 흐물해진 살, 껍질이 살에서 분리되면 버리세요.","Ammonia, mushy meat, shell separating from flesh — done."],
 fzt:["냉동 새우는 수산물 중 최장수 — 소분해 두면 1년을 갑니다.","Frozen shrimp is the freezer's longest-lived seafood — portioned, a full year."]},
{id:"오징어",ko:"오징어",en:"Squid",e:"🦑",g:"seafood",rt:null,fr:[1,2,"d"],fz:[3,6,"M"],
 tip:["내장과 먹물을 제거하고 씻어 물기 없이 냉장 — 손질이 곧 보관법이에요.","Gut it, remove the ink, wash and dry — the cleaning is the storage."],
 exp:["표면이 투명하고 반점이 선명할수록 신선 — 하얗게 변하면 시간이 지난 거예요.","Translucent skin with vivid spots means fresh; turning opaque white means time has passed."],
 bad:["붉은 기가 도는 살, 미끈한 점액, 시큼한 냄새면 버리세요.","Pinkish flesh, slime, sourness — toss."],
 fzt:["통째보다 손질 후 냉동 — 얼렸다 해동하면 오히려 연해져서 볶음용으론 이득이에요.","Freeze cleaned, not whole — thawing actually tenderizes it for stir-fries."]},
{id:"조개",ko:"조개",en:"Clams",e:"🦪",g:"seafood",rt:null,fr:[1,2,"d"],fz:[3,null,"M"],
 tip:["살아 있어야 신선한 식재료 — 밀폐하지 말고 젖은 천을 덮어 냉장, 물에 담그면 죽어요.","They must stay alive — damp cloth, not sealed, never submerged in the fridge."],
 exp:["입 벌린 조개를 톡 쳐서 닫히면 산 것, 안 닫히면 죽은 것 — 죽은 조개는 조리 전에 골라내세요.","Tap an open clam: closing means alive. Cull the dead before cooking."],
 bad:["냄새가 시큼하거나 껍데기가 깨진 채 벌어져 있으면 버리세요.","Sour smell or cracked-and-gaping shells — discard."],
 fzt:["해감 후 살만 발라 국물과 함께 냉동 — 3개월, 육수 낼 때 그대로 투하해요.","Purge, shuck, freeze the meat in its liquor — 3 months, straight into broth."]},
{id:"굴",ko:"굴",en:"Oysters",e:"🦪",g:"seafood",rt:null,fr:[1,2,"d"],fz:[2,3,"M"],
 tip:["봉지굴은 유통되는 바닷물째 냉장 — 개봉하면 그날이 데드라인이라 생각하세요.","Bagged oysters keep in their brine, chilled — opening day is deadline day."],
 exp:["생식용과 가열용 표시를 꼭 확인하세요 — 가열용 굴 생식은 노로바이러스 지름길이에요.","Check the raw-vs-cooking label — eating cooking-grade raw is the norovirus express."],
 bad:["살이 퍼지고 우윳빛 물이 탁해지며 신 냄새가 나면 버리세요.","Spreading flesh, cloudy milky liquid, sourness — toss."],
 fzt:["가열용으로만 — 국·전용 2~3개월, 해동 후 생식은 절대 금지예요.","Cooking use only — 2–3 months for soups and jeon; never raw after thawing."]},
{id:"게",ko:"게",en:"Crab",e:"🦀",g:"seafood",rt:null,fr:[1,2,"d"],fz:[2,3,"M"],
 tip:["산 게는 젖은 천을 덮어 냉장 채소칸에 — 죽은 지 오래된 게는 독소가 생겨 위험해요.","Live crabs under damp cloth in the crisper — long-dead crab develops toxins."],
 exp:["게는 죽는 순간부터 시계가 빨라져요 — 죽었다면 바로 쪄서 보관하세요.","The clock sprints once a crab dies — steam it immediately."],
 bad:["암모니아 냄새와 흐물해진 살, 검게 변한 내장이 보이면 버리세요.","Ammonia, mushy meat, blackened innards — done."],
 fzt:["쪄서 식힌 뒤 냉동 2~3개월 — 생물 냉동보다 살이 덜 빠져요.","Steam, cool, then freeze — 2–3 months, and the meat holds better than raw-frozen."]},
{id:"멸치",ko:"멸치 (건)",en:"Dried Anchovies",e:"🐠",g:"seafood",rt:[2,4,"w"],fr:[1,3,"M"],fz:[6,12,"M"],
 tip:["'건어물은 냉동실'이 국룰 — 실온에 두면 기름이 산패해 쓴맛이 나요.","Dried seafood lives in the freezer — the Korean rule. Room temp turns the oils bitter."],
 exp:["노랗게 변하고 쩐내가 나면 산패 — 국물용으로도 쓴맛이 우러나니 버리세요.","Yellowed and rancid-smelling means oxidized — it turns even broth bitter. Toss."],
 bad:["가루가 많이 생기고 곰팡이 냄새, 벌레가 보이면 버리세요.","Excess powder, musty smell, or pantry bugs — discard."],
 fzt:["지퍼백에 소분해 냉동 — 얼린 채 바로 육수 내면 됩니다, 1년.","Portion into zip bags, freeze a year — straight from freezer to broth pot."]},
{id:"김",ko:"김",en:"Gim (laver)",e:"🍙",g:"seafood",rt:[1,2,"M"],fr:null,fz:[6,12,"M"],
 tip:["실온 밀봉 1~2개월, 장기 보관은 냉동 — 냉장은 오히려 습기가 차서 눅눅해져요.","Sealed at room temp for a month or two; freezer for the long haul. The fridge, oddly, makes it soggy."],
 exp:["눅눅해진 김은 마른 팬에 살짝 구우면 바삭함이 부활해요 — 버릴 단계가 아니에요.","Soggy gim revives in a dry pan — not trash yet."],
 bad:["보라색·붉은 반점이나 쿰쿰한 곰팡내가 나면 버리세요.","Purple-red patches or a musty smell — toss."],
 fzt:["지퍼백째 냉동 후 꺼내면 바로 바삭 — 김 애호가의 표준 보관법이에요.","Freeze in the bag; it comes out crisp — the connoisseur's default."]},
{id:"미역",ko:"미역 (건)",en:"Dried Seaweed",e:"🌊",g:"seafood",rt:[1,2,"y"],fr:null,fz:null,
 tip:["건미역은 밀봉해 서늘하고 어두운 곳 — 습기만 차단하면 1~2년 가는 장수 식재료예요.","Sealed, cool and dark — block humidity and dried miyeok lives 1–2 years."],
 exp:["불린 미역은 별개예요 — 냉장 2~3일 안에 드세요.","Rehydrated is another story — 2–3 fridge days."],
 bad:["흰 가루가 소금기인지 곰팡이인지 — 쿰쿰한 냄새가 나면 곰팡이예요.","White dust could be salt or mold — a musty smell means mold."],
 fzt:["건조 상태 자체가 최강 보존이라 냉동은 불필요해요.","Drying already is the preservation — the freezer adds nothing."]},
{id:"생선회",ko:"생선회",en:"Sashimi",e:"🍣",g:"seafood",rt:null,fr:[1,null,"d"],fz:null,
 tip:["회는 '보관'하는 음식이 아니라 '오늘 끝내는' 음식 — 남으면 냉장 24시간이 절대 한계예요.","Sashimi isn't stored, it's finished — 24 fridge hours is the absolute ceiling for leftovers."],
 exp:["다음 날 회는 생식 대신 구이·탕으로 — 익히면 하루의 여유가 생겨요.","Day-two sashimi becomes grilled fish or stew — cooking buys one more day."],
 bad:["표면이 마르며 광택이 사라지고 비린내가 진해지면 생식 불가예요.","Dry dull surface and intensifying fishiness — no longer raw-safe."],
 fzt:["가정 냉동고는 회 냉동에 부적합 — 식감과 안전 모두 잃어요.","Home freezers fail sashimi on both texture and safety."]},
/* ---- 유제품·계란 dairy (10) ---- */
{id:"우유",ko:"우유",en:"Milk",e:"🥛",g:"dairy",rt:null,fr:[2,3,"d"],fz:[1,null,"M"],
 tip:["문쪽 선반은 온도가 널뛰어요 — 우유는 냉장고 안쪽에. 개봉 후엔 표시 기한과 무관하게 2~3일이에요.","Door shelves swing warm — milk belongs deep inside. Once opened, 2–3 days regardless of the label."],
 exp:["미개봉 우유는 소비기한까지 안전 — 소비기한은 유통기한보다 며칠 더 긴 '진짜 마지노선'이에요.","Unopened milk is safe to the use-by date — the real line, a few days past the old sell-by."],
 bad:["덩어리지고 시큼한 냄새 — 의심되면 컵에 조금 따라 냄새부터 확인하세요.","Clumps and sourness — when unsure, pour a little and smell first."],
 fzt:["팩째는 터져요 — 용기에 옮겨 냉동 1개월, 해동 후 흔들어 요리용으로 쓰세요.","Cartons burst — decant, freeze a month, shake after thawing, use for cooking."]},
{id:"치즈",ko:"치즈",en:"Cheese",e:"🧀",g:"dairy",rt:null,fr:[2,4,"w"],fz:[2,3,"M"],
 tip:["랩 대신 유산지·왁스랩이 이상적 — 치즈도 숨을 쉬어요. 슬라이스는 개봉 후 1~2주.","Parchment beats plastic wrap — cheese breathes. Opened slices get 1–2 weeks."],
 exp:["하드치즈의 곰팡이는 그 부분+여유 1cm를 도려내면 OK, 슬라이스·연성치즈 곰팡이는 통째로 버리세요.","Hard cheese mold cuts away with a 1 cm margin; moldy soft or sliced cheese goes out whole."],
 bad:["암모니아 냄새와 미끈한 표면, 포장 안 물기가 탁해지면 버리세요.","Ammonia smell, slick surface, cloudy package liquid — toss."],
 fzt:["갈아서 냉동하면 2~3개월 — 피자·그라탕용으론 완벽, 그냥 먹기엔 퍼석해요.","Shred and freeze 2–3 months — perfect melted, crumbly eaten plain."]},
{id:"요거트",ko:"요거트",en:"Yogurt",e:"🍶",g:"dairy",rt:null,fr:[3,5,"d"],fz:[1,2,"M"],
 tip:["떠먹을 땐 반드시 마른 수저 — 침이 닿는 순간 기한이 급격히 짧아져요.","Dry spoon only — one dip of a used spoon slashes the timeline."],
 exp:["위에 고인 노란 물은 유청이라 저어 먹으면 돼요 — 상한 게 아니에요.","The yellow liquid on top is whey — stir it in, it's not spoilage."],
 bad:["곰팡이 점, 부풀어 오른 뚜껑, 톡 쏘는 알코올 냄새면 버리세요.","Mold dots, a bulging lid, a sharp boozy smell — done."],
 fzt:["얼리면 유산균 일부는 자지만 죽지 않아요 — 얼린 요거트 그대로 디저트예요.","Freezing puts cultures to sleep, not death — frozen yogurt is its own dessert."]},
{id:"버터",ko:"버터",en:"Butter",e:"🧈",g:"dairy",rt:null,fr:[1,3,"M"],fz:[6,9,"M"],
 tip:["냄새를 잘 흡수해요 — 밀폐용기 필수. 일주일 쓸 만큼만 잘라 꺼내 쓰세요.","Butter absorbs fridge odors — airtight box, and slice off just a week's worth at a time."],
 exp:["색이 진해진 겉면은 산화층 — 얇게 깎아내면 속은 새 버터예요.","A darkened surface is just oxidation — shave it thin and the inside is new."],
 bad:["쩐내(산패취)와 신맛, 얼룩덜룩한 변색이면 버리세요.","Rancid smell, sour taste, blotchy color — toss."],
 fzt:["포장째 냉동 6~9개월 — 사용 분량만 냉장으로 옮겨가며 쓰세요.","Freeze in its wrapper 6–9 months — migrate blocks to the fridge as needed."]},
{id:"생크림",ko:"생크림",en:"Fresh Cream",e:"🍦",g:"dairy",rt:null,fr:[1,3,"d"],fz:[1,2,"M"],
 tip:["개봉한 생크림은 3일의 재료 — 남을 것 같으면 계획부터 세우고 개봉하세요.","Opened cream is a three-day ingredient — plan the whole carton before you open it."],
 exp:["미개봉이라도 냉장 필수 제품 — 문쪽 말고 안쪽 칸에 두세요.","Even sealed it demands the cold back shelf, never the door."],
 bad:["덩어리지고 신 냄새가 나면 휘핑도 요리도 불가 — 버리세요.","Clumped and sour whips into nothing — discard."],
 fzt:["휘핑해서 짜놓은 모양 그대로 냉동 — 코코아 위에 얼린 채 올리면 됩니다.","Whip first, pipe dollops, freeze — drop them frozen onto hot cocoa."]},
{id:"계란",ko:"계란",en:"Eggs",e:"🥚",g:"dairy",rt:null,fr:[3,5,"w"],fz:null,
 tip:["뾰족한 쪽이 아래로, 문쪽 말고 안쪽 칸에 — 한국 세척란은 반드시 냉장 유지예요.","Pointy end down, inside shelf not the door — Korean washed eggs must stay refrigerated."],
 exp:["물에 넣어 가라앉으면 신선, 뜨면 오래된 것 — 산란일자 기준 냉장 3~5주예요.","The float test: sinkers are fresh, floaters are old. 3–5 weeks from the laying date."],
 bad:["깨보면 흰자가 물처럼 퍼지고 유황 냄새가 나면 버리세요.","Watery spreading whites and a sulfur smell — toss."],
 fzt:["껍질째 냉동은 터져요 — 풀어서 냉동하면 요리용 1년, 완숙 흰자는 냉동 불가예요.","In-shell freezing bursts — beaten eggs freeze a year for cooking; boiled whites never."]},
{id:"두유",ko:"두유",en:"Soy Milk",e:"🥛",g:"dairy",rt:null,fr:[2,3,"d"],fz:null,
 tip:["멸균팩 미개봉은 실온 가능하지만, 개봉하면 냉장 2~3일 — 우유와 같은 시계로 움직여요.","Sealed aseptic packs sit at room temp, but opened cartons run on milk's clock: 2–3 fridge days."],
 exp:["미개봉 멸균 두유의 라벨 기한은 수개월 — 재난 대비용으로도 쓰이는 이유죠.","Unopened aseptic soy milk rides its months-long label — hence its spot in emergency kits."],
 bad:["덩어리·부푼 팩·신맛이면 버리세요.","Clumps, a puffed pack, sourness — done."],
 fzt:["얼리면 단백질이 분리돼 두부 같은 질감 — 음용은 비권장이에요.","Freezing separates the protein into tofu-ish curds — not for drinking after."]},
{id:"아이스크림",ko:"아이스크림",en:"Ice Cream",e:"🍦",g:"dairy",rt:null,fr:null,fz:[2,4,"M"],
 tip:["냉동실 문쪽 말고 안쪽 깊숙이 — 온도 출렁임이 얼음 결정(서걱임)의 범인이에요.","Deep inside the freezer, never the door — temperature swings grow those gritty ice crystals."],
 exp:["아이스크림엔 유통기한 표시가 없어요(빙과류 면제) — 대신 개봉 후 2~4개월 내 품질이 최선이에요.","Ice cream legally carries no expiry in Korea — quality peaks within 2–4 months of opening instead."],
 bad:["녹았다 다시 언 흔적(표면 얼음막·수축)이 있으면 식중독 위험 — 맛 이전에 안전 문제예요.","Signs of melt-and-refreeze — ice film, shrinkage — are a safety issue, not just texture."],
 fzt:["표면에 랩을 밀착시키고 뚜껑을 덮으면 얼음 결정을 늦출 수 있어요.","Press wrap onto the surface under the lid to slow crystal growth."]},
{id:"연유",ko:"연유",en:"Condensed Milk",e:"🥛",g:"dairy",rt:null,fr:[2,3,"w"],fz:[3,null,"M"],
 tip:["개봉 후 밀폐 냉장 — 캔이라면 유리병으로 옮기세요, 캔 그대로는 산화돼요.","Sealed in the fridge after opening — decant cans into glass; open cans oxidize."],
 exp:["당도가 높아 오래 버티는 편 — 그래도 2~3주 안에 쓰는 게 맛의 전성기예요.","All that sugar buys time — but 2–3 weeks is the flavor's prime."],
 bad:["색이 진한 갈색으로 변하고 덩어리지면 버리세요.","Deep browning and clumps — toss."],
 fzt:["당분 때문에 완전히 얼지 않아 떠 쓰기 좋아요 — 3개월.","Sugar keeps it scoopably soft-frozen — 3 months."]},
{id:"마가린",ko:"마가린",en:"Margarine",e:"🧈",g:"dairy",rt:null,fr:[1,2,"M"],fz:[6,null,"M"],
 tip:["버터와 같은 규칙 — 밀폐 냉장, 표면이 마르지 않게 랩을 밀착하세요.","Butter's rules apply — sealed and chilled, wrap pressed onto the surface."],
 exp:["개봉 후 1~2개월 — 표면에 물방울이 맺히면 품질 저하 신호예요.","1–2 months opened — beading water on top signals decline."],
 bad:["쩐내와 얼룩진 변색, 곰팡이 점이 보이면 버리세요.","Rancid smell, blotches, mold specks — done."],
 fzt:["통째 냉동 6개월 — 베이킹용은 냉동 상태에서 강판에 갈아 쓰는 것도 요령이에요.","Freeze 6 months — baker's trick: grate it straight from frozen."]},
/* ---- 곡물·면·빵 grain (12) ---- */
{id:"쌀",ko:"쌀",en:"Rice (uncooked)",e:"🌾",g:"grain",rt:[1,2,"M"],fr:[3,6,"M"],fz:null,
 tip:["밀폐용기+서늘한 곳, 여름엔 냉장 야채칸이 최고의 쌀통이에요. 마른 고추나 마늘을 넣으면 벌레 예방.","Airtight and cool; in summer the crisper is the best rice bin. A dried chili inside deters bugs."],
 exp:["쌀은 상하기보다 '맛이 늙어요' — 도정일로부터 여름 1개월, 겨울 2개월이 밥맛의 전성기예요.","Rice ages more than it spoils — flavor peaks within a month of milling in summer, two in winter."],
 bad:["쌀벌레, 곰팡내, 쌀알이 푸르스름하게 변하면 버리세요.","Weevils, mustiness, or greenish grains — toss."],
 fzt:["생쌀 냉동은 불필요 — 냉장 밀폐로 충분해요.","Raw rice doesn't need the freezer — sealed refrigeration covers it."]},
{id:"밥",ko:"밥 (지은 밥)",en:"Cooked Rice",e:"🍚",g:"grain",rt:null,fr:[3,5,"d"],fz:[1,2,"M"],
 tip:["실온 방치는 2시간까지 — 밥의 바실러스 세레우스균은 재가열로도 안 죽는 독소를 만들어요.","Two hours max at room temp — rice's Bacillus cereus makes a toxin reheating can't kill."],
 exp:["보온 밥솥 보관도 하루가 한계 — 그 이상은 누렇게 변하며 맛과 안전 모두 떨어져요.","Even the warmer setting caps at a day — beyond that it yellows and risks rise."],
 bad:["쉰내가 나고 밥알이 끈적하게 실처럼 늘어나면 버리세요.","A sour smell and sticky stringing grains — done."],
 fzt:["한 김 나간 따뜻한 밥을 1공기씩 랩핑 냉동 — 전자레인지 2분이면 갓 지은 맛, 이게 정석이에요.","Wrap still-warm portions and freeze — two microwave minutes brings back fresh-cooked. This is the way."]},
{id:"식빵",ko:"식빵",en:"Sliced Bread",e:"🍞",g:"grain",rt:[2,3,"d"],fr:null,fz:[2,3,"M"],
 tip:["의외의 진실: 냉장 보관은 최악이에요 — 빵의 전분 노화가 실온보다 6배 빨라져요. 실온 2~3일, 그 이상은 냉동.","Counterintuitive truth: the fridge is bread's worst enemy — starch staling runs six times faster. Counter for days, freezer beyond."],
 exp:["여름 장마철엔 곰팡이가 하루 만에도 펴요 — 습한 계절만 기한을 반으로 접으세요.","In humid monsoon weeks mold can bloom overnight — halve the timeline in wet season."],
 bad:["곰팡이가 한 장에만 보여도 봉지째 버리세요 — 포자는 이미 전체에 퍼져 있어요.","Mold on one slice condemns the loaf — spores have already toured the bag."],
 fzt:["2장씩 소분 냉동, 얼린 채 토스터에 — 갓 구운 식감이 부활해요.","Freeze in pairs; toast straight from frozen — bakery texture, resurrected."]},
{id:"떡",ko:"떡",en:"Tteok (rice cake)",e:"🍡",g:"grain",rt:[1,null,"d"],fr:null,fz:[1,2,"M"],
 tip:["떡의 운명은 사는 순간 결정 — 오늘 먹을 것만 남기고 즉시 냉동하세요. 냉장은 딱딱하게 굳는 지름길이에요.","Tteok's fate is sealed at purchase — keep today's share, freeze the rest immediately. The fridge is the express lane to rock-hard."],
 exp:["실온 하루가 전부 — 여름엔 반나절 만에 쉬어요.","One counter day is all it gets — half that in summer."],
 bad:["시큼한 냄새와 끈적한 실, 곰팡이 점이 보이면 버리세요.","Sourness, sticky strings, mold dots — toss."],
 fzt:["한 번 먹을 만큼 랩핑 냉동 — 찌거나 에어프라이어에 돌리면 말랑함이 돌아와요.","Wrap single servings; steaming or air-frying brings the softness back."]},
{id:"라면",ko:"라면",en:"Instant Ramen",e:"🍜",g:"grain",rt:[5,6,"M"],fr:null,fz:null,
 tip:["직사광선 없는 서늘한 곳 — 유탕면의 기름은 빛과 열에 산패해요.","Cool and out of sunlight — the fried noodles' oil goes rancid under light and heat."],
 exp:["라면 유통기한은 제조일로부터 약 5~6개월, 소비기한은 그보다 더 — 다만 기름 쩐내가 나면 기한 전이라도 버리세요.","The label runs ~5–6 months from production, the true use-by longer — but a rancid whiff overrules any date."],
 bad:["면에서 쩐내(산패취)가 나거나 기름이 배어 나온 자국이 있으면 버리세요.","Rancid-smelling noodles or grease-stained packaging — done."],
 fzt:["냉동·냉장 불필요 — 건조식품은 실온이 제자리예요.","No fridge, no freezer — dried goods belong at room temp."]},
{id:"국수",ko:"국수 (건면)",en:"Dried Noodles",e:"🍝",g:"grain",rt:[1,2,"y"],fr:null,fz:null,
 tip:["개봉 후엔 밀폐용기에 세워 보관 — 습기와 벌레만 막으면 1~2년 가는 장수 식품이에요.","Stand them in an airtight jar after opening — block moisture and bugs, and they live for years."],
 exp:["기한이 지나도 상태가 멀쩡하면 대부분 먹을 수 있어요 — 삶아보면 답이 나와요.","Past-date but intact usually means edible — the boiling pot renders the verdict."],
 bad:["곰팡내, 벌레, 면이 얼룩덜룩 변색되면 버리세요.","Mustiness, bugs, mottled discoloration — toss."],
 fzt:["불필요 — 대신 삶은 면은 냉장 하루, 그 이상은 포기하세요.","Unneeded — though boiled noodles get one fridge day, no more."]},
{id:"밀가루",ko:"밀가루",en:"Flour",e:"🌾",g:"grain",rt:[6,8,"M"],fr:[1,null,"y"],fz:[2,null,"y"],
 tip:["밀폐용기가 전부예요 — 종이포대 그대로 두면 습기와 화랑곡나방(쌀벌레)의 표적이 돼요.","An airtight container is everything — the paper bag invites moisture and pantry moths."],
 exp:["통밀가루는 배아 기름 때문에 백밀가루의 절반 — 3개월이 기준이에요.","Whole wheat lives half as long as white — three months, thanks to germ oils."],
 bad:["쩐내·시큼한 냄새, 덩어리, 움직이는 점(벌레)이 보이면 버리세요.","Rancid or sour smells, clumps, or moving specks — discard."],
 fzt:["장기 보관은 냉동 2년 — 벌레 알까지 잡는 가장 확실한 방법이에요.","The freezer buys two years — and kills any stowaway eggs."]},
{id:"오트밀",ko:"오트밀",en:"Oatmeal",e:"🥣",g:"grain",rt:[1,null,"y"],fr:null,fz:null,
 tip:["밀폐해 서늘하고 어두운 곳 — 개봉 후에도 1년을 버티는 든든한 곡물이에요.","Sealed, cool and dark — a dependable grain that holds a year even opened."],
 exp:["끓여둔 오트밀은 별개 — 냉장 3~4일이에요.","Cooked porridge is another matter — 3–4 fridge days."],
 bad:["기름 쩐내와 쿰쿰한 냄새, 벌레가 보이면 버리세요.","Oily rancidity, mustiness, or bugs — toss."],
 fzt:["건조 상태는 불필요, 끓인 오트밀은 소분 냉동 1개월 가능해요.","Dry needs nothing; cooked freezes a month in portions."]},
{id:"시리얼",ko:"시리얼",en:"Cereal",e:"🥣",g:"grain",rt:[2,3,"M"],fr:null,fz:null,
 tip:["봉지를 돌돌 말아 집게로 — 시리얼의 적은 상함이 아니라 눅눅함이에요.","Roll and clip the inner bag — cereal's enemy isn't spoilage, it's sog."],
 exp:["개봉 후 2~3개월 — 눅눅해진 건 오븐이나 에어프라이어 2~3분으로 부활해요.","2–3 months opened — a few oven minutes re-crisps the soggy."],
 bad:["기름 쩐내가 나거나 벌레가 보이면 버리세요.","Rancid smell or pantry bugs — done."],
 fzt:["불필요 — 밀폐만 잘하면 실온으로 충분해요.","Unnecessary — a good seal at room temp is all it takes."]},
{id:"파스타",ko:"파스타 (건면)",en:"Dry Pasta",e:"🍝",g:"grain",rt:[1,2,"y"],fr:null,fz:null,
 tip:["유리병에 옮겨 담으면 보관도 인테리어도 해결 — 습기 없는 실온이면 충분해요.","Glass jars solve storage and shelf styling at once — dry room temp is all it asks."],
 exp:["계란 없는 건파스타는 기한을 한참 넘겨도 대부분 무사해요 — 향이 정상인지가 기준이에요.","Egg-free dry pasta sails far past its date — the nose is the judge."],
 bad:["곰팡내나 얼룩, 벌레가 보이면 버리세요.","Musty smell, stains, or bugs — toss."],
 fzt:["건면은 불필요, 삶은 면은 올리브유에 버무려 냉장 3일이에요.","Dry needs nothing; cooked pasta tossed in oil keeps three fridge days."]},
{id:"케이크",ko:"케이크 (생크림)",en:"Cream Cake",e:"🍰",g:"grain",rt:null,fr:[1,2,"d"],fz:[1,null,"M"],
 tip:["생크림 케이크는 구매 즉시 냉장, 1~2일이 전부 — 상자째 두지 말고 밀폐용기나 뒤집은 볼을 덮어주세요.","Fresh-cream cake goes straight to the fridge for a day or two — swap the cardboard box for a sealed cover."],
 exp:["케이크의 기한은 크림이 정해요 — 시트는 멀쩡해도 크림이 먼저 셔요.","The cream sets the deadline — sponge outlives frosting every time."],
 bad:["크림이 누렇게 변하고 시큼한 냄새, 물이 배어 나오면 버리세요.","Yellowing cream, sourness, weeping liquid — done."],
 fzt:["조각으로 랩핑 냉동 1개월 — 반해동 상태의 아이스크림 케이크 식감도 별미예요.","Wrap slices and freeze a month — half-thawed, it's an ice-cream cake bonus."]},
{id:"견과류",ko:"견과류",en:"Nuts",e:"🥜",g:"grain",rt:[1,null,"M"],fr:[3,6,"M"],fz:[1,null,"y"],
 tip:["견과의 적은 산패 — 개봉 후엔 냉장, 대량 구매분은 냉동이 정석이에요.","Rancidity is the enemy — fridge after opening, freezer for the bulk bag."],
 exp:["실온 개봉 상태로는 한 달 — 쩐내가 나기 시작하면 이미 늦은 거예요.","A month at room temp once opened — by the time it smells rancid, it's past."],
 bad:["쓴맛·쩐내, 표면 기름 번들거림, 곰팡이가 보이면 버리세요.","Bitterness, rancid smell, oily sheen, or mold — toss."],
 fzt:["냉동 1년 — 얼린 채 먹어도 식감이 거의 그대로예요.","A frozen year — and they eat nearly the same straight from the freezer."]},
/* ---- 소스·양념 sauce (15) ---- */
{id:"간장",ko:"간장",en:"Soy Sauce",e:"🍶",g:"sauce",rt:[2,3,"M"],fr:[6,12,"M"],fz:null,
 tip:["개봉 후엔 냉장이 향을 지켜요 — 실온도 가능하지만 색과 풍미가 빨리 진해져요.","Refrigeration guards the aroma after opening — room temp works, but color and flavor deepen fast."],
 exp:["소금 덕에 사실상 안전 기한은 매우 길어요 — 문제는 상함이 아니라 풍미 저하예요.","Salt makes it nearly unspoilable — the real decline is flavor, not safety."],
 bad:["표면에 흰 막(산막효모)이 뜨거나 곰팡내가 나면 버리세요.","A white film on top or mustiness — discard."],
 fzt:["염도가 높아 얼지도 않아요 — 냉동 불필요.","Too salty to even freeze — the freezer is moot."]},
{id:"고추장",ko:"고추장",en:"Gochujang",e:"🌶️",g:"sauce",rt:null,fr:[6,12,"M"],fz:null,
 tip:["개봉 후엔 냉장 — 뜨거나 젖은 수저가 닿는 순간부터 곰팡이 카운트다운이 시작돼요.","Fridge after opening — a wet or used spoon starts the mold countdown."],
 exp:["발효식품이라 기한이 길지만, 표면이 마르며 검어지는 건 산화 — 걷어내고 쓰면 돼요.","Fermentation buys long life; a darkened dry surface is oxidation — scrape and carry on."],
 bad:["흰 곰팡이 점이나 시큼한 알코올 냄새(과발효)가 나면 버리세요.","White mold spots or a sharp boozy over-ferment — toss."],
 fzt:["얼지 않는 염도·당도 — 냉장으로 충분해요.","Salt and sugar keep it from freezing anyway — the fridge suffices."]},
{id:"된장",ko:"된장",en:"Doenjang",e:"🫘",g:"sauce",rt:null,fr:[6,12,"M"],fz:null,
 tip:["표면을 평평하게 눌러 랩을 밀착하면 산화가 늦어져요 — 마른 수저 원칙은 여기서도 철칙.","Press the surface flat and lay wrap directly on it — and the dry-spoon rule is law here too."],
 exp:["된장은 시간이 지날수록 색이 진해질 뿐 — 전통 된장은 해를 넘겨도 먹어요.","Doenjang merely darkens with age — traditional batches cross years."],
 bad:["푸른·검은 곰팡이(흰 골마지는 걷어내면 OK)와 쿰쿰함을 넘은 부패취면 버리세요.","Blue-black mold is the end (white film scrapes off); so is rot beyond the usual funk."],
 fzt:["냉장으로 충분 — 장류는 냉동고에 자리를 내주지 않아도 돼요.","The fridge is enough — fermented pastes don't need freezer real estate."]},
{id:"식용유",ko:"식용유",en:"Cooking Oil",e:"🫗",g:"sauce",rt:[1,3,"M"],fr:null,fz:null,
 tip:["가스레인지 옆은 최악의 자리 — 열과 빛을 피해 어두운 찬장에 두세요.","Beside the stove is the worst seat in the house — dark cupboard, away from heat and light."],
 exp:["개봉 후 1~3개월이 풍미의 전성기 — 큰 통보다 작은 통을 자주 사는 게 이득이에요.","Flavor peaks 1–3 months after opening — small bottles bought often beat the big jug."],
 bad:["쩐내와 끈적해진 병 입구, 튀길 때 거품이 심하면 산패예요.","Rancid smell, a sticky spout, violent foaming when frying — oxidized."],
 fzt:["냉장하면 뿌옇게 굳지만 상한 건 아니에요 — 그래도 실온 어두운 곳이 정석이에요.","Refrigeration clouds it harmlessly — but a dark shelf remains the right home."]},
{id:"참기름",ko:"참기름",en:"Sesame Oil",e:"🫗",g:"sauce",rt:[4,6,"M"],fr:null,fz:null,
 tip:["어두운 유리병에 담아 서늘한 찬장 — 냉장하면 굳고, 볕에 두면 향이 달아나요.","Dark glass, cool cupboard — the fridge solidifies it, sunlight steals the aroma."],
 exp:["참기름의 기한은 향의 기한 — 고소함이 옅어지면 새로 짤 때가 된 거예요.","Sesame oil expires when its nuttiness does — faded aroma means time for a fresh bottle."],
 bad:["쩐내가 고소함을 이기면 산패 — 요리 전체를 망치니 버리세요.","When rancidity beats nuttiness, it's oxidized — it will ruin the whole dish."],
 fzt:["불필요 — 서늘한 실온이 참기름의 제자리예요.","Unneeded — cool room temperature is where it belongs."]},
{id:"마요네즈",ko:"마요네즈",en:"Mayonnaise",e:"🥚",g:"sauce",rt:null,fr:[1,2,"M"],fz:null,
 tip:["개봉 후 냉장 필수 — 입구에 묻은 마요네즈를 닦아두면 곰팡이를 예방해요.","Fridge after opening, no exceptions — and wipe the nozzle to keep mold away."],
 exp:["시판 마요네즈는 산도 덕에 생각보다 튼튼해요 — 개봉 후 1~2개월이 기준이에요.","Commercial mayo's acidity makes it sturdier than feared — 1–2 months opened."],
 bad:["기름이 분리돼 노란 물이 고이고 신 냄새가 나면 버리세요.","Separated oil pooling yellow with a sour smell — done."],
 fzt:["얼리면 유화가 깨져 기름 반 덩어리 반 — 냉동 절대 비권장이에요.","Freezing shatters the emulsion into oil and curds — never."]},
{id:"케첩",ko:"케첩",en:"Ketchup",e:"🍅",g:"sauce",rt:null,fr:[4,6,"M"],fz:null,
 tip:["개봉 후 냉장, 거꾸로 세워두면 늘 바로 나와요 — 병 입구 관리가 수명 관리예요.","Fridge after opening, stored upside-down for instant flow — a clean nozzle is a long life."],
 exp:["산도와 당도의 합작으로 개봉 후에도 4~6개월 — 소스계의 장수 챔피언이에요.","Acid plus sugar buys 4–6 opened months — the condiment longevity champion."],
 bad:["뚜껑 안쪽 곰팡이, 부풀어 오른 병, 알코올 냄새면 버리세요.","Mold under the cap, a bulging bottle, boozy smell — toss."],
 fzt:["불필요 — 냉장이면 충분하고, 얼리면 질감만 나빠져요.","Unneeded — freezing only wrecks the texture."]},
{id:"고춧가루",ko:"고춧가루",en:"Gochugaru",e:"🌶️",g:"sauce",rt:[1,null,"M"],fr:[3,6,"M"],fz:[1,2,"y"],
 tip:["고춧가루의 집은 냉동실이에요 — 실온에선 색이 바래고 벌레가 꼬여요. 지퍼백+밀폐용기 이중 방어.","Gochugaru lives in the freezer — room temp fades the red and invites bugs. Zip bag inside a sealed box."],
 exp:["색이 검붉게 변하면 매운 향도 함께 죽은 것 — 김장용은 그해 것을 쓰세요.","Darkened red means the aroma died with it — kimjang deserves this year's batch."],
 bad:["덩어리지고 곰팡내가 나거나 벌레가 보이면 버리세요.","Clumping, mustiness, or bugs — discard."],
 fzt:["냉동해도 얼어붙지 않아 바로 떠 쓸 수 있어요 — 1~2년 색이 살아 있어요.","It never freezes solid — scoop straight from the freezer, red for years."]},
{id:"소금",ko:"소금",en:"Salt",e:"🧂",g:"sauce",rt:"inf",fr:null,fz:null,
 tip:["소금은 상하지 않는 유일한 조미료급 광물 — 습기로 굳는 것만 막으면 돼요. 쌀알 몇 톨이 습기를 먹어줘요.","Salt is a mineral and simply cannot spoil — just fight clumping. A few rice grains in the shaker absorb the damp."],
 exp:["유통기한 표시가 있어도 형식일 뿐 — 소금의 진짜 기한은 무기한이에요.","Any printed date is a formality — salt's true shelf life is forever."],
 bad:["상하지 않지만, 이물질이 섞였거나 이상한 냄새를 흡수했다면 교체하세요.","It can't rot — but replace it if contaminated or if it's absorbed odd odors."],
 fzt:["냉동은 무의미 — 건조한 실온이 소금의 왕좌예요.","Freezing is meaningless — a dry shelf is salt's throne."]},
{id:"설탕",ko:"설탕",en:"Sugar",e:"🍬",g:"sauce",rt:"inf",fr:null,fz:null,
 tip:["밀폐만 하면 반영구적 — 굳었다면 식빵 한 조각을 하루 넣어두세요, 마법처럼 풀려요.","Sealed, it's essentially eternal — hardened sugar softens overnight with a slice of bread inside."],
 exp:["설탕도 유통기한 표시가 무의미한 식품 — 습기와 개미만 조심하면 됩니다.","Another food whose date means nothing — guard against moisture and ants, that's all."],
 bad:["상하진 않지만 벌레가 들었거나 젖어서 발효 냄새가 나면 버리세요.","It won't spoil — but bugs or wet fermented smells mean replacement."],
 fzt:["불필요 — 건조 밀폐가 전부예요.","Unneeded — dry and sealed is the whole game."]},
{id:"꿀",ko:"꿀",en:"Honey",e:"🍯",g:"sauce",rt:"inf",fr:null,fz:null,
 tip:["꿀은 3000년 된 피라미드에서도 멀쩡히 발견된 식품 — 밀봉해 실온에 두고, 젖은 수저만 피하세요.","Honey has been found edible in 3,000-year-old pyramids — sealed at room temp, dry spoons only."],
 exp:["하얗게 굳는 결정화는 상함이 아니라 자연현상 — 40도 중탕이면 원상복구예요.","White crystallization isn't spoilage, it's physics — a warm-water bath restores it."],
 bad:["표면에 거품이 일며 시큼한 술 냄새(발효)가 나면 수분이 들어간 것 — 버리세요.","Foaming with a sour boozy smell means water got in and fermentation began — toss."],
 fzt:["냉장·냉동 모두 결정화만 앞당겨요 — 실온이 정답이에요.","Fridge and freezer only hasten crystallizing — room temp is the answer."]},
{id:"식초",ko:"식초",en:"Vinegar",e:"🫙",g:"sauce",rt:"inf",fr:null,fz:null,
 tip:["식초 자체가 방부제 — 뚜껑만 잘 닫아 서늘한 곳에 두면 사실상 무기한이에요.","Vinegar is the preservative — capped and cool, it's effectively immortal."],
 exp:["바닥의 뿌연 침전물이나 실 같은 덩어리(초모)는 무해해요 — 걸러 쓰면 됩니다.","Cloudy sediment or a jellyfish-like 'mother' is harmless — strain and continue."],
 bad:["상하는 일은 거의 없지만, 향이 완전히 죽었다면 교체할 때예요.","It rarely goes bad — but a dead aroma means it's time for new."],
 fzt:["불필요 — 산도가 모든 걸 지켜요.","Unneeded — the acidity guards everything."]},
{id:"굴소스",ko:"굴소스",en:"Oyster Sauce",e:"🦪",g:"sauce",rt:null,fr:[3,6,"M"],fz:null,
 tip:["개봉 후 반드시 냉장 — 이름처럼 굴 추출물이 들어 있어 간장류보다 훨씬 예민해요.","Fridge after opening, always — the oyster extract makes it far touchier than soy sauce."],
 exp:["개봉 후 3~6개월 — 병 입구가 검게 굳으면 닦아내며 쓰세요.","3–6 opened months — wipe the darkening crust at the spout as you go."],
 bad:["곰팡이, 부푼 뚜껑, 시큼한 냄새가 나면 버리세요.","Mold, a bulging cap, sourness — done."],
 fzt:["불필요 — 냉장 필수, 냉동은 과잉이에요.","The fridge is mandatory; the freezer, overkill."]},
{id:"카레가루",ko:"카레가루",en:"Curry Powder",e:"🍛",g:"sauce",rt:[3,6,"M"],fr:null,fz:null,
 tip:["개봉 후 밀폐해 서늘한 곳 — 향신료의 기한은 곧 향의 기한이에요.","Sealed and cool after opening — a spice expires when its scent does."],
 exp:["오래된 카레가루는 상하기보다 밍밍해져요 — 향이 죽었으면 양을 늘려도 소용없어요.","Old curry powder fades rather than spoils — and no amount compensates for dead aroma."],
 bad:["덩어리지고 곰팡내가 나거나 벌레가 보이면 버리세요.","Clumps, mustiness, or bugs — toss."],
 fzt:["장기 보관은 냉동도 가능하지만 밀폐 실온으로 충분해요.","The freezer works for hoards, but a sealed jar at room temp suffices."]},
{id:"후추",ko:"후추",en:"Pepper",e:"⚫",g:"sauce",rt:[1,3,"y"],fr:null,fz:null,
 tip:["통후추로 사서 그때그때 갈아 쓰는 게 향 수명 3배 — 간 후추는 1년, 통후추는 3년이에요.","Buy whole and grind fresh — triple the aromatic life. Ground lasts a year; whole, three."],
 exp:["기한이 지나도 위험하진 않아요 — 다만 향 없는 후추는 검은 먼지일 뿐이죠.","Expired pepper isn't dangerous — just scentless black dust."],
 bad:["곰팡내가 나거나 습기로 덩어리지면 교체하세요.","Mustiness or moisture clumps — replace."],
 fzt:["불필요 — 건조 밀폐면 충분해요.","Unneeded — dry and sealed covers it."]},
/* ---- 반찬·요리 cooked (14) ---- */
{id:"김치",ko:"김치",en:"Kimchi",e:"🥬",g:"cooked",rt:[1,2,"d"],fr:[1,3,"M"],fz:null,
 tip:["국물에 잠기게 꾹꾹 눌러 밀폐 — 공기에 닿은 김치부터 무르고 셔져요. 덜 때는 마른 집게로.","Press it under its own brine, sealed — air-exposed kimchi softens and sours first. Dry tongs only."],
 exp:["김치에 유통기한은 없어요 — 신김치는 상한 게 아니라 다음 단계(찌개·볶음)로 진화한 거예요.","Kimchi has no expiry — sour kimchi hasn't spoiled, it's evolved into stew and fried-rice form."],
 bad:["하얀 골마지는 걷어내면 되지만, 파란 곰팡이나 군내(꼬릿한 부패취)가 나면 버리세요.","White yeast film scrapes off; blue mold or a rotten stink does not — toss."],
 fzt:["얼리면 아삭함이 죽어요 — 볶음·찌개용으로만 냉동하고, 보관은 김치냉장고 온도(-1~0도)가 정답이에요.","Freezing kills the crunch — freeze only for stew duty. The real answer is kimchi-fridge temperature."]},
{id:"국-찌개",ko:"국·찌개",en:"Soup & Stew",e:"🍲",g:"cooked",rt:null,fr:[2,3,"d"],fz:[1,2,"M"],
 tip:["한 김 식혀 바로 냉장 — '아침에 끓였으니까'라는 실온 방치가 여름 식중독의 주범이에요.","Cool briefly, then straight to the fridge — the 'I boiled it this morning' counter habit is summer's top poisoner."],
 exp:["냉장 2~3일, 꺼낼 때마다 팔팔 끓이면 하루씩 연장 — 단, 끓이기 반복은 3회가 한계예요.","2–3 fridge days; a full re-boil buys another — but three re-boils is the ceiling."],
 bad:["표면 거품과 시큼한 냄새, 국물이 끈적해지면 버리세요 — 끓여도 독소는 남아요.","Surface foam, sourness, viscous broth — reheating won't remove the toxins. Toss."],
 fzt:["국물째 소분 냉동 1~2개월 — 두부·감자는 얼면 식감이 망가지니 건져내고 얼리세요.","Freeze in portions, broth and all — but fish out tofu and potato first; they don't survive."]},
{id:"카레",ko:"카레 (조리)",en:"Cooked Curry",e:"🍛",g:"cooked",rt:null,fr:[2,3,"d"],fz:[1,null,"M"],
 tip:["'하룻밤 묵힌 카레'는 실온이 아니라 냉장에서 — 카레 실온 방치는 웰치균(클로스트리디움)의 배양접시예요.","Overnight curry means overnight in the fridge — room-temp curry is a petri dish for Clostridium perfringens."],
 exp:["웰치균은 끓여도 포자가 살아남아요 — 냉장 2~3일, 재가열은 바닥까지 저어가며 팔팔.","Its spores survive boiling — 2–3 fridge days, and reheat to a full rolling bubble, stirring deep."],
 bad:["신 냄새와 표면의 흰 막, 부글거리는 기포가 보이면 버리세요.","Sourness, white film, spontaneous bubbles — done."],
 fzt:["감자만 건져내고 소분 냉동 1개월 — 감자는 해동하면 스펀지가 돼요.","Pull the potatoes, then freeze portions a month — potato thaws into sponge."]},
{id:"볶음밥",ko:"볶음밥",en:"Fried Rice",e:"🍳",g:"cooked",rt:null,fr:[1,2,"d"],fz:[1,null,"M"],
 tip:["'볶음밥 증후군'이라는 말이 있을 정도 — 밥의 세레우스균 독소는 볶아도 안 죽어요. 실온 2시간이 한계.","'Fried rice syndrome' is a real term — Bacillus cereus toxin survives the wok. Two counter hours, no more."],
 exp:["냉장 1~2일 — 만들 때부터 남길 분량은 뜨거울 때 소분해두는 게 요령이에요.","1–2 fridge days — portion the leftovers while still hot, at cooking time."],
 bad:["쉰내와 끈적해진 밥알 — 재가열로 냄새가 가려져도 독소는 그대로예요.","Sour smell, sticky grains — reheating masks the smell, not the toxin."],
 fzt:["납작하게 펴서 냉동 1개월 — 얼린 채 팬에 부수며 볶으면 갓 만든 맛이에요.","Freeze flat for a month — crumble it frozen straight into the pan."]},
{id:"나물",ko:"나물 반찬",en:"Seasoned Greens",e:"🥗",g:"cooked",rt:null,fr:[2,3,"d"],fz:null,
 tip:["무친 나물은 손맛과 함께 세균도 들어간 음식 — 냉장 2~3일이 전부예요. 참기름은 먹기 직전에 두르면 하루 이득.","Hand-mixed namul carries hand bacteria too — 2–3 fridge days. Adding the sesame oil at serving buys a day."],
 exp:["반찬 중 가장 짧은 축 — 덜어 먹고 원통엔 손대지 않는 게 연장 비법이에요.","Among the shortest-lived banchan — serve portions out, never eat from the container."],
 bad:["시큼한 냄새와 미끈한 물기가 생기면 버리세요.","Sourness and slimy liquid — toss."],
 fzt:["얼리면 물러져요 — 데친 상태(무치기 전)로는 냉동 가능하니 순서를 기억하세요.","Dressed namul freezes into mush — but blanched-undressed freezes fine. Order matters."]},
{id:"전",ko:"전·부침개",en:"Jeon (pancakes)",e:"🥞",g:"cooked",rt:null,fr:[2,3,"d"],fz:[1,null,"M"],
 tip:["완전히 식힌 뒤 키친타월과 함께 밀폐 — 뜨거운 채 덮으면 증기가 눅눅함과 세균을 함께 키워요.","Cool completely, seal with a paper towel inside — trapping steam breeds both sog and bacteria."],
 exp:["명절 전은 냉장 2~3일 — 3일차엔 전찌개로 변신시키는 게 전통의 지혜예요.","Holiday jeon gets 2–3 fridge days — day three is when tradition turns it into jeon stew."],
 bad:["쉰내와 미끈한 표면, 밀가루 반죽 부분의 곰팡이를 확인하세요.","Sour smell, slick surface, mold on the batter parts — check all three."],
 fzt:["한 장씩 유산지 끼워 냉동 — 팬이나 에어프라이어 재가열이면 갓 부친 맛의 90%예요.","Freeze with parchment between; pan or air-fryer reheating recovers 90% of fresh."]},
{id:"튀김",ko:"튀김",en:"Fried Food",e:"🍤",g:"cooked",rt:null,fr:[2,3,"d"],fz:[1,null,"M"],
 tip:["식힘망에서 완전히 식힌 뒤 키친타월 깔고 밀폐 냉장 — 기름종이째 봉지 보관은 눅눅함 제조기예요.","Cool fully on a rack, then paper-lined and sealed — leaving it in the greasy paper bag is a sog machine."],
 exp:["냉장 2~3일 — 부활의 열쇠는 전자레인지가 아니라 에어프라이어예요.","2–3 fridge days — resurrection comes from the air fryer, never the microwave."],
 bad:["기름 쩐내와 눅눅함을 넘은 시큼함이 나면 버리세요.","Past sogginess into rancid-sour territory — toss."],
 fzt:["냉동 1개월 — 얼린 채 에어프라이어 180도면 바삭함이 돌아와요.","A frozen month — 180°C air-fried straight from frozen brings the crunch home."]},
{id:"치킨",ko:"치킨 (먹다 남은)",en:"Leftover Fried Chicken",e:"🍗",g:"cooked",rt:null,fr:[1,2,"d"],fz:[1,null,"M"],
 tip:["상자째 냉장은 금지 — 상자가 습기를 머금어요. 밀폐용기로 옮기고 실온 2시간을 넘기지 마세요.","Never refrigerate in the box — cardboard traps moisture. Transfer to a sealed container within two hours."],
 exp:["냉장 1~2일 — 다음 날 치킨은 에어프라이어 7분이 정답이에요.","1–2 fridge days — next-day chicken means seven air-fryer minutes."],
 bad:["시큼한 냄새와 미끈해진 튀김옷, 살이 회색빛이면 버리세요.","Sourness, slimy batter, graying meat — done."],
 fzt:["살만 발라 냉동하면 볶음밥·샐러드 토핑으로 한 달을 살아요.","Pull the meat and freeze — a month of fried-rice and salad toppings."]},
{id:"피자",ko:"피자 (남은)",en:"Leftover Pizza",e:"🍕",g:"cooked",rt:null,fr:[3,4,"d"],fz:[1,2,"M"],
 tip:["박스째 냉장고 투입은 자리 낭비+눅눅함 — 조각을 랩핑하거나 밀폐용기에 옮기세요.","Boxing the whole thing into the fridge wastes space and crisp — wrap slices or use a container."],
 exp:["냉장 3~4일 — 프라이팬에 뚜껑 덮고 데우면 바닥은 바삭, 치즈는 주르륵 부활해요.","3–4 fridge days — a covered skillet revives crisp bottom and molten cheese at once."],
 bad:["토핑이 미끈해지고 시큼한 냄새가 나면 버리세요.","Slimy toppings and a sour smell — toss."],
 fzt:["조각 랩핑 냉동 1~2개월 — 얼린 채 오븐 직행이 가장 맛있어요.","Wrap slices, freeze 1–2 months — straight from freezer to oven is best."]},
{id:"만두",ko:"만두 (냉동)",en:"Frozen Dumplings",e:"🥟",g:"cooked",rt:null,fr:[1,2,"d"],fz:[1,2,"M"],
 tip:["개봉한 냉동만두는 지퍼백으로 옮겨 공기를 빼세요 — 봉지째 두면 서리와 냉동상(化傷)이 맛을 갉아먹어요.","Move opened bags into zip bags, air squeezed out — frost and freezer burn eat the flavor otherwise."],
 exp:["미개봉은 라벨 기한, 개봉 후엔 1~2개월 내 소진이 맛의 마지노선이에요.","Sealed rides the label; opened, 1–2 months is the flavor deadline."],
 bad:["피가 하얗게 마르고(냉동상) 냉동실 냄새가 배면 안전해도 맛은 끝 — 해동 후 쉰내면 버리세요.","White freezer-burned skins taste of the freezer — safe but done. Post-thaw sourness means toss."],
 fzt:["해동한 만두는 재냉동 금지 — 그대로 쪄서 냉장 1~2일 내 드세요.","Never refreeze thawed dumplings — steam them and finish within two fridge days."]},
{id:"두부",ko:"두부",en:"Tofu",e:"⬜",g:"cooked",rt:null,fr:[2,3,"d"],fz:[3,null,"M"],
 tip:["개봉 후 남은 두부는 물에 잠기게 담아 냉장, 물은 매일 교체 — 이 한 수로 3일을 삽니다.","Submerge leftovers in water, changed daily — that single move buys three days."],
 exp:["미개봉 포장두부는 표시 기한까지, 개봉하면 2~3일 — 물이 뿌예지면 교체 신호예요.","Sealed packs ride the label; opened gets 2–3 days. Cloudy water means change it."],
 bad:["표면이 미끈하고 시큼한 냄새, 붉은 점이 보이면 버리세요.","Slimy surface, sourness, pink spots — done."],
 fzt:["얼리면 언두부(동두부)가 돼요 — 스펀지 질감이 양념을 쫙 빨아들이는 별개의 재료로 재탄생해요.","Freezing creates 'frozen tofu' — a spongy rebirth that drinks up sauce like nothing else."]},
{id:"어묵",ko:"어묵",en:"Eomuk (fish cake)",e:"🍢",g:"cooked",rt:null,fr:[2,3,"d"],fz:[2,3,"M"],
 tip:["개봉 후엔 밀폐해 냉장 2~3일 — 수분이 많은 가공품이라 보기보다 빨리 상해요.","Sealed and chilled, 2–3 days — all that moisture turns it faster than it looks."],
 exp:["표면이 살짝 끈적하면 뜨거운 물을 부어 헹구고 바로 조리 — 그 이상이면 포기하세요.","Slight surface tack rinses off with hot water for immediate cooking — beyond that, let go."],
 bad:["시큼한 냄새와 실처럼 늘어나는 점액이 생기면 버리세요.","Sourness and stringy slime — toss."],
 fzt:["소분 냉동 2~3개월 — 얼린 채 국에 바로 투하해도 돼요.","Portion and freeze 2–3 months — straight from freezer into the broth."]},
{id:"묵",ko:"묵",en:"Muk (jelly)",e:"🍮",g:"cooked",rt:null,fr:[1,2,"d"],fz:null,
 tip:["물에 잠기게 담아 냉장 — 묵은 수분이 생명이라 공기 노출이 곧 노화예요.","Store submerged in water — muk lives on moisture; air exposure is aging."],
 exp:["냉장 1~2일 — 굳어서 딱딱해진 묵은 끓는 물에 데치면 탱글함이 돌아와요.","1–2 fridge days — hardened muk springs back after a quick blanch."],
 bad:["표면이 녹아내리듯 미끈해지고 신 냄새가 나면 버리세요.","A melting-slick surface and sourness — done."],
 fzt:["얼리면 조직이 부서져 물이 됩니다 — 냉동 불가 식품이에요.","Freezing shatters it into water — a genuinely unfreezable food."]},
{id:"계란찜",ko:"계란찜",en:"Steamed Egg",e:"🍮",g:"cooked",rt:null,fr:[1,2,"d"],fz:null,
 tip:["계란 요리는 냉장 1~2일이 전부 — 만든 그릇째 랩을 밀착해 두세요.","Egg dishes get 1–2 fridge days, period — wrap pressed right onto the surface."],
 exp:["재가열하면 수분이 빠져 질겨져요 — 물 한 스푼 넣고 데우면 부드러움이 삽니다.","Reheating toughens it — a spoon of water in the microwave keeps the silk."],
 bad:["시큼한 냄새와 물이 흥건히 분리되면 버리세요.","Sourness and pooling separated water — toss."],
 fzt:["얼리면 벌집처럼 구멍이 숭숭 — 계란찜은 냉동 불가예요.","Freezing turns it to honeycomb — steamed egg cannot be frozen."]},
/* ---- 음료 drink (12) ---- */
{id:"생수",ko:"생수 (개봉)",en:"Bottled Water (opened)",e:"💧",g:"drink",rt:[1,null,"d"],fr:[2,3,"d"],fz:null,
 tip:["입 대고 마신 병은 세균 배양 중 — 컵에 따라 마시면 냉장 2~3일, 입 댔으면 당일이에요.","Drinking from the bottle starts a culture — poured into cups it lasts 2–3 fridge days; lips-on means today."],
 exp:["미개봉 생수의 기한은 물이 아니라 페트병의 기한 — 오래되면 용기 성분이 우러날 수 있어요.","Unopened water's date is really the bottle's date — old plastic can leach."],
 bad:["이상한 맛·냄새, 부유물이 보이면 버리세요.","Off taste, odd smell, floaters — discard."],
 fzt:["가득 찬 병은 얼면 터져요 — 얼릴 거면 2할을 비우세요.","Full bottles burst frozen — pour off a fifth first."]},
{id:"주스",ko:"주스",en:"Juice",e:"🧃",g:"drink",rt:null,fr:[7,10,"d"],fz:[2,3,"M"],
 tip:["개봉 후 시판 살균주스는 냉장 7~10일, 착즙주스는 1~2일 — '살균'과 '생'의 차이가 곧 기한의 차이예요.","Pasteurized juice gets 7–10 opened days; fresh-pressed, 1–2. Pasteurization is the whole difference."],
 exp:["팩이 부풀었다면 이미 발효 중 — 기한과 무관하게 버리세요.","A puffed carton means fermentation is underway — toss regardless of date."],
 bad:["탄산처럼 톡 쏘는 맛(발효), 시큼한 술 냄새, 곰팡이면 버리세요.","Fizzy tang, boozy sourness, mold — done."],
 fzt:["얼음틀에 얼려 주스 얼음으로 — 물 대신 넣으면 밍밍해질 일이 없어요.","Freeze into juice cubes — chilling drinks without diluting them."]},
{id:"탄산음료",ko:"탄산음료",en:"Soda",e:"🥤",g:"drink",rt:[1,null,"d"],fr:[2,3,"d"],fz:null,
 tip:["탄산의 기한은 상함이 아니라 김빠짐 — 뚜껑을 꽉 닫고 세워서 냉장하면 2~3일은 버텨요.","Soda expires by flatness, not spoilage — capped tight and upright, the fizz holds 2–3 days."],
 exp:["미개봉은 기한이 길지만 페트병은 서서히 탄산이 새요 — 캔·유리가 더 오래가요.","Sealed bottles slowly bleed CO₂ through the plastic — cans and glass hold longest."],
 bad:["단맛이 이상하게 변하거나 부유물이 생기면 버리세요.","Warped sweetness or floaters — toss."],
 fzt:["얼리면 터져요 — 탄산+팽창의 조합은 냉동고 청소 예약이에요.","Freezing means explosion — carbonation plus expansion books you a freezer cleanup."]},
{id:"원두",ko:"커피 원두",en:"Coffee Beans",e:"☕",g:"drink",rt:[2,4,"w"],fr:null,fz:[1,2,"M"],
 tip:["불투명 밀폐용기+서늘한 곳 — 냉장고는 습기와 냄새를 옮기는 최악의 원두 창고예요.","Opaque airtight jar, cool spot — the fridge is the worst bean cellar, all humidity and odors."],
 exp:["로스팅 후 2~4주가 향의 전성기 — 원두는 상하기 전에 '심심해져요'.","Flavor peaks 2–4 weeks post-roast — beans go boring long before they go bad."],
 bad:["기름이 눅진하게 배어나며 쩐내가 나면 산패 — 버리세요.","Greasy sheen and rancid smell mean oxidized — toss."],
 fzt:["대량 구매분만 1회분씩 소분 냉동 — 꺼내면 해동 없이 바로 갈아야 결로를 피해요.","Freeze bulk buys in single doses — grind straight from frozen to dodge condensation."]},
{id:"내린커피",ko:"내린 커피",en:"Brewed Coffee",e:"☕",g:"drink",rt:null,fr:[1,2,"d"],fz:null,
 tip:["내린 순간부터 산화 시작 — 실온 반나절, 냉장 1~2일이 마실 만한 한계예요.","Oxidation starts at the drip — half a day out, 1–2 days chilled is the drinkable window."],
 exp:["다음 날 커피는 아이스로 — 향은 갔지만 카페인은 성실하게 남아 있어요.","Day-two coffee goes over ice — the aroma left, the caffeine stayed loyal."],
 bad:["시큼함이 산미가 아닌 쉰맛으로 변하고 표면에 막이 생기면 버리세요.","When sour turns spoiled and a film forms — done."],
 fzt:["커피 얼음으로 얼리는 것만 유일한 정답 — 아이스커피가 안 밍밍해져요.","Coffee ice cubes are the one right answer — iced coffee that never waters down."]},
{id:"티백",ko:"차 티백",en:"Tea Bags",e:"🍵",g:"drink",rt:[1,2,"y"],fr:null,fz:null,
 tip:["밀폐+어두운 곳 — 차의 적은 습기, 빛, 그리고 옆에 둔 향신료의 냄새예요.","Sealed and dark — tea's enemies are moisture, light, and the spice jar next door."],
 exp:["기한 지난 티백도 대부분 안전 — 향이 죽었을 뿐이니 두 개 넣고 우리면 돼요.","Past-date tea is almost always safe — just faded. Double-bag the brew."],
 bad:["곰팡내가 나거나 티백에 얼룩이 보이면 버리세요.","Mustiness or stained bags — toss."],
 fzt:["불필요 — 건조 밀폐가 전부예요.","Unneeded — dry and sealed is everything."]},
{id:"와인",ko:"와인 (개봉)",en:"Wine (opened)",e:"🍷",g:"drink",rt:null,fr:[3,5,"d"],fz:null,
 tip:["마개를 다시 꽂아 세워서 냉장 — 레드와인도 개봉 후엔 냉장고행이에요, 마시기 전 잠깐 꺼내두면 됩니다.","Re-cork, stand upright, refrigerate — yes, red too. Just let it warm a touch before pouring."],
 exp:["개봉 후 3~5일 — 그 뒤엔 마시는 와인에서 요리하는 와인으로 신분이 바뀌어요.","3–5 opened days — after that it changes careers from drinking wine to cooking wine."],
 bad:["식초 냄새와 갈변, 탁해짐이 오면 요리용으로도 끝이에요.","Vinegar smell, browning, haze — done even for the pan."],
 fzt:["남은 와인은 얼음틀에 — 요리용 와인 큐브는 프로의 냉동실 풍경이에요.","Ice-cube leftover wine — cooking cubes are a pro freezer staple."]},
{id:"맥주",ko:"맥주",en:"Beer",e:"🍺",g:"drink",rt:null,fr:[1,null,"d"],fz:null,
 tip:["개봉한 맥주의 수명은 몇 시간 — 탄산과 향이 함께 증발해요. 미개봉은 서늘한 곳, 빛을 피해서.","Opened beer lives hours, not days — fizz and aroma leave together. Sealed bottles want cool darkness."],
 exp:["미개봉도 기한이 있어요 — 맥주는 와인과 달리 숙성이 아니라 노화만 해요.","Even sealed beer has a clock — unlike wine, it only ages downward."],
 bad:["빛에 오래 노출된 병맥주의 스컹크 같은 냄새(일광취)면 버리세요.","The skunky smell of light-struck bottles — pour it out."],
 fzt:["냉동실 급랭은 잊고 꺼내는 순간 폭발 사고 — 타이머 없이는 넣지 마세요.","Flash-chilling ends in explosion the moment you forget — no timer, no freezer."]},
{id:"소주",ko:"소주",en:"Soju",e:"🍶",g:"drink",rt:"inf",fr:null,fz:null,
 tip:["증류주는 유통기한이 없어요 — 개봉했더라도 마개를 닫아두면 사실상 무기한이에요.","Distilled spirits carry no expiry — even opened, capped soju is effectively immortal."],
 exp:["기한 대신 보관만 — 직사광선을 피하면 몇 년이 지나도 그 소주예요.","No dates, just storage — out of sunlight, it's the same soju years later."],
 bad:["상할 일은 없지만 이물질이 들어갔다면 버리세요.","It cannot spoil — but contamination means discard."],
 fzt:["도수 때문에 얼지 않아요 — 냉동실 슬러시 소주는 그래서 가능한 거예요.","The alcohol keeps it from freezing — hence the freezer-slush soju trick."]},
{id:"막걸리",ko:"막걸리",en:"Makgeolli",e:"🍶",g:"drink",rt:null,fr:[2,3,"d"],fz:null,
 tip:["생막걸리는 살아 있는 술 — 미개봉도 냉장 필수, 세워서 보관하고 열 땐 천천히(분수 주의).","Fresh makgeolli is alive — refrigerate even sealed, store upright, open slowly (it fountains)."],
 exp:["미개봉 냉장 열흘 안팎, 개봉 후 2~3일 — 날짜가 지날수록 시어지는 건 발효의 숙명이에요.","About ten sealed fridge days, 2–3 once opened — souring with time is fermentation's destiny."],
 bad:["신맛을 넘어 쓴맛이 나고 덩어리가 심하면 버리세요.","Past sour into bitter with heavy curds — done."],
 fzt:["얼리면 층 분리에 탄산 폭발 위험 — 냉동 비권장이에요.","Freezing splits the layers and risks a fizzy burst — not recommended."]},
{id:"이온음료",ko:"이온음료",en:"Sports Drink",e:"🥤",g:"drink",rt:null,fr:[1,2,"d"],fz:null,
 tip:["당분 많은 음료는 개봉 후 세균의 놀이터 — 입 대고 마셨다면 당일, 따라 마셨다면 1~2일이에요.","Sugary drinks become playgrounds once opened — lips-on means today; poured, 1–2 days."],
 exp:["운동 가방 속 반쯤 마신 병이 가장 위험한 케이스 — 체온+당분 조합이에요.","The half-drunk bottle in a gym bag is the worst case — body heat plus sugar."],
 bad:["탁해지고 부유물, 신 냄새가 생기면 버리세요.","Cloudiness, floaters, sourness — toss."],
 fzt:["살짝 얼려 슬러시로 마시는 건 가능 — 단, 병을 가득 채운 채 얼리면 터져요.","Slush-freezing works — just never with a full bottle."]},
{id:"스무디",ko:"스무디·착즙주스",en:"Smoothie / Fresh Juice",e:"🥤",g:"drink",rt:null,fr:[1,null,"d"],fz:[1,null,"M"],
 tip:["살균 없이 간 생과일은 '마시는 생식품' — 만든 즉시 마시고, 남으면 냉장 24시간이 한계예요.","Unpasteurized blends are drinkable raw produce — drink at once; leftovers get 24 fridge hours."],
 exp:["색이 변하는 건 산화(갈변)로 맛 문제지만, 냄새가 변하면 안전 문제예요.","Color change is oxidation — a taste issue. Smell change is a safety issue."],
 bad:["층 분리를 넘어 거품이 일고 시큼한 술 냄새가 나면 발효 — 버리세요.","Separation is normal; foaming with boozy sourness is fermentation — toss."],
 fzt:["얼음틀 냉동 1개월 — 다시 갈면 즉석 스무디로 부활해요.","Ice-tray freeze for a month — re-blend into an instant smoothie."]},
];
if (typeof module !== "undefined") module.exports = FOODS;
